// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.archforce.ath.rds.grpc.proto;

public interface AddUserInfoParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.AddUserInfoParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
