// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.archforce.ath.rds.grpc.proto;

/**
 * <pre>
 * 查询股份持仓信息返回参数
 * </pre>
 *
 * Protobuf type {@code com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams}
 */
public  final class QueryStockInfoResponseParams extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams)
    QueryStockInfoResponseParamsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryStockInfoResponseParams.newBuilder() to construct.
  private QueryStockInfoResponseParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryStockInfoResponseParams() {
    messageType_ = 0;
    queryResultCode_ = 0;
    userInfo_ = "";
    lastIndex_ = 0L;
    totalNum_ = 0L;
    stockInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryStockInfoResponseParams(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            messageType_ = rawValue;
            break;
          }
          case 18: {
            com.archforce.ath.rds.grpc.proto.CommonParams.Builder subBuilder = null;
            if (commonParams_ != null) {
              subBuilder = commonParams_.toBuilder();
            }
            commonParams_ = input.readMessage(com.archforce.ath.rds.grpc.proto.CommonParams.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(commonParams_);
              commonParams_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            queryResultCode_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            userInfo_ = s;
            break;
          }
          case 40: {

            lastIndex_ = input.readInt64();
            break;
          }
          case 48: {

            totalNum_ = input.readInt64();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              stockInfo_ = new java.util.ArrayList<com.archforce.ath.rds.grpc.proto.StockInfo>();
              mutable_bitField0_ |= 0x00000040;
            }
            stockInfo_.add(
                input.readMessage(com.archforce.ath.rds.grpc.proto.StockInfo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        stockInfo_ = java.util.Collections.unmodifiableList(stockInfo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponseParams_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponseParams_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams.class, com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGETYPE_FIELD_NUMBER = 1;
  private int messageType_;
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.MessageType messageType = 1;</code>
   */
  public int getMessageTypeValue() {
    return messageType_;
  }
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.MessageType messageType = 1;</code>
   */
  public com.archforce.ath.rds.grpc.proto.MessageType getMessageType() {
    com.archforce.ath.rds.grpc.proto.MessageType result = com.archforce.ath.rds.grpc.proto.MessageType.valueOf(messageType_);
    return result == null ? com.archforce.ath.rds.grpc.proto.MessageType.UNRECOGNIZED : result;
  }

  public static final int COMMONPARAMS_FIELD_NUMBER = 2;
  private com.archforce.ath.rds.grpc.proto.CommonParams commonParams_;
  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
   */
  public boolean hasCommonParams() {
    return commonParams_ != null;
  }
  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
   */
  public com.archforce.ath.rds.grpc.proto.CommonParams getCommonParams() {
    return commonParams_ == null ? com.archforce.ath.rds.grpc.proto.CommonParams.getDefaultInstance() : commonParams_;
  }
  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
   */
  public com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder getCommonParamsOrBuilder() {
    return getCommonParams();
  }

  public static final int QUERYRESULTCODE_FIELD_NUMBER = 3;
  private int queryResultCode_;
  /**
   * <pre>
   * 查询结果代码
   * </pre>
   *
   * <code>int32 queryResultCode = 3;</code>
   */
  public int getQueryResultCode() {
    return queryResultCode_;
  }

  public static final int USERINFO_FIELD_NUMBER = 4;
  private volatile java.lang.Object userInfo_;
  /**
   * <pre>
   * 用户私有信息
   * </pre>
   *
   * <code>string userInfo = 4;</code>
   */
  public java.lang.String getUserInfo() {
    java.lang.Object ref = userInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userInfo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户私有信息
   * </pre>
   *
   * <code>string userInfo = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUserInfoBytes() {
    java.lang.Object ref = userInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTINDEX_FIELD_NUMBER = 5;
  private long lastIndex_;
  /**
   * <pre>
   * 条目索引号 最后一笔查询结果的索引号,当"lastIndex+1=totalNum"时表示已经查询到最后的记录;组合个数为0时,该值为-1
   * </pre>
   *
   * <code>int64 lastIndex = 5;</code>
   */
  public long getLastIndex() {
    return lastIndex_;
  }

  public static final int TOTALNUM_FIELD_NUMBER = 6;
  private long totalNum_;
  /**
   * <pre>
   * 条目总数
   * </pre>
   *
   * <code>int64 totalNum = 6;</code>
   */
  public long getTotalNum() {
    return totalNum_;
  }

  public static final int STOCKINFO_FIELD_NUMBER = 7;
  private java.util.List<com.archforce.ath.rds.grpc.proto.StockInfo> stockInfo_;
  /**
   * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
   */
  public java.util.List<com.archforce.ath.rds.grpc.proto.StockInfo> getStockInfoList() {
    return stockInfo_;
  }
  /**
   * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
   */
  public java.util.List<? extends com.archforce.ath.rds.grpc.proto.StockInfoOrBuilder> 
      getStockInfoOrBuilderList() {
    return stockInfo_;
  }
  /**
   * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
   */
  public int getStockInfoCount() {
    return stockInfo_.size();
  }
  /**
   * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
   */
  public com.archforce.ath.rds.grpc.proto.StockInfo getStockInfo(int index) {
    return stockInfo_.get(index);
  }
  /**
   * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
   */
  public com.archforce.ath.rds.grpc.proto.StockInfoOrBuilder getStockInfoOrBuilder(
      int index) {
    return stockInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageType_ != com.archforce.ath.rds.grpc.proto.MessageType.ORIGINAL_MESSAGE.getNumber()) {
      output.writeEnum(1, messageType_);
    }
    if (commonParams_ != null) {
      output.writeMessage(2, getCommonParams());
    }
    if (queryResultCode_ != 0) {
      output.writeInt32(3, queryResultCode_);
    }
    if (!getUserInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userInfo_);
    }
    if (lastIndex_ != 0L) {
      output.writeInt64(5, lastIndex_);
    }
    if (totalNum_ != 0L) {
      output.writeInt64(6, totalNum_);
    }
    for (int i = 0; i < stockInfo_.size(); i++) {
      output.writeMessage(7, stockInfo_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageType_ != com.archforce.ath.rds.grpc.proto.MessageType.ORIGINAL_MESSAGE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, messageType_);
    }
    if (commonParams_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCommonParams());
    }
    if (queryResultCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, queryResultCode_);
    }
    if (!getUserInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userInfo_);
    }
    if (lastIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, lastIndex_);
    }
    if (totalNum_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, totalNum_);
    }
    for (int i = 0; i < stockInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, stockInfo_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams)) {
      return super.equals(obj);
    }
    com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams other = (com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams) obj;

    boolean result = true;
    result = result && messageType_ == other.messageType_;
    result = result && (hasCommonParams() == other.hasCommonParams());
    if (hasCommonParams()) {
      result = result && getCommonParams()
          .equals(other.getCommonParams());
    }
    result = result && (getQueryResultCode()
        == other.getQueryResultCode());
    result = result && getUserInfo()
        .equals(other.getUserInfo());
    result = result && (getLastIndex()
        == other.getLastIndex());
    result = result && (getTotalNum()
        == other.getTotalNum());
    result = result && getStockInfoList()
        .equals(other.getStockInfoList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + messageType_;
    if (hasCommonParams()) {
      hash = (37 * hash) + COMMONPARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getCommonParams().hashCode();
    }
    hash = (37 * hash) + QUERYRESULTCODE_FIELD_NUMBER;
    hash = (53 * hash) + getQueryResultCode();
    hash = (37 * hash) + USERINFO_FIELD_NUMBER;
    hash = (53 * hash) + getUserInfo().hashCode();
    hash = (37 * hash) + LASTINDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastIndex());
    hash = (37 * hash) + TOTALNUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalNum());
    if (getStockInfoCount() > 0) {
      hash = (37 * hash) + STOCKINFO_FIELD_NUMBER;
      hash = (53 * hash) + getStockInfoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 查询股份持仓信息返回参数
   * </pre>
   *
   * Protobuf type {@code com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams)
      com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParamsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponseParams_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponseParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams.class, com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams.Builder.class);
    }

    // Construct using com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStockInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      messageType_ = 0;

      if (commonParamsBuilder_ == null) {
        commonParams_ = null;
      } else {
        commonParams_ = null;
        commonParamsBuilder_ = null;
      }
      queryResultCode_ = 0;

      userInfo_ = "";

      lastIndex_ = 0L;

      totalNum_ = 0L;

      if (stockInfoBuilder_ == null) {
        stockInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        stockInfoBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponseParams_descriptor;
    }

    public com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams getDefaultInstanceForType() {
      return com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams.getDefaultInstance();
    }

    public com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams build() {
      com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams buildPartial() {
      com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams result = new com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.messageType_ = messageType_;
      if (commonParamsBuilder_ == null) {
        result.commonParams_ = commonParams_;
      } else {
        result.commonParams_ = commonParamsBuilder_.build();
      }
      result.queryResultCode_ = queryResultCode_;
      result.userInfo_ = userInfo_;
      result.lastIndex_ = lastIndex_;
      result.totalNum_ = totalNum_;
      if (stockInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          stockInfo_ = java.util.Collections.unmodifiableList(stockInfo_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.stockInfo_ = stockInfo_;
      } else {
        result.stockInfo_ = stockInfoBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams) {
        return mergeFrom((com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams other) {
      if (other == com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams.getDefaultInstance()) return this;
      if (other.messageType_ != 0) {
        setMessageTypeValue(other.getMessageTypeValue());
      }
      if (other.hasCommonParams()) {
        mergeCommonParams(other.getCommonParams());
      }
      if (other.getQueryResultCode() != 0) {
        setQueryResultCode(other.getQueryResultCode());
      }
      if (!other.getUserInfo().isEmpty()) {
        userInfo_ = other.userInfo_;
        onChanged();
      }
      if (other.getLastIndex() != 0L) {
        setLastIndex(other.getLastIndex());
      }
      if (other.getTotalNum() != 0L) {
        setTotalNum(other.getTotalNum());
      }
      if (stockInfoBuilder_ == null) {
        if (!other.stockInfo_.isEmpty()) {
          if (stockInfo_.isEmpty()) {
            stockInfo_ = other.stockInfo_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureStockInfoIsMutable();
            stockInfo_.addAll(other.stockInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.stockInfo_.isEmpty()) {
          if (stockInfoBuilder_.isEmpty()) {
            stockInfoBuilder_.dispose();
            stockInfoBuilder_ = null;
            stockInfo_ = other.stockInfo_;
            bitField0_ = (bitField0_ & ~0x00000040);
            stockInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStockInfoFieldBuilder() : null;
          } else {
            stockInfoBuilder_.addAllMessages(other.stockInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int messageType_ = 0;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.MessageType messageType = 1;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.MessageType messageType = 1;</code>
     */
    public Builder setMessageTypeValue(int value) {
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.MessageType messageType = 1;</code>
     */
    public com.archforce.ath.rds.grpc.proto.MessageType getMessageType() {
      com.archforce.ath.rds.grpc.proto.MessageType result = com.archforce.ath.rds.grpc.proto.MessageType.valueOf(messageType_);
      return result == null ? com.archforce.ath.rds.grpc.proto.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.MessageType messageType = 1;</code>
     */
    public Builder setMessageType(com.archforce.ath.rds.grpc.proto.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      messageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.MessageType messageType = 1;</code>
     */
    public Builder clearMessageType() {
      
      messageType_ = 0;
      onChanged();
      return this;
    }

    private com.archforce.ath.rds.grpc.proto.CommonParams commonParams_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.archforce.ath.rds.grpc.proto.CommonParams, com.archforce.ath.rds.grpc.proto.CommonParams.Builder, com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder> commonParamsBuilder_;
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
     */
    public boolean hasCommonParams() {
      return commonParamsBuilder_ != null || commonParams_ != null;
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
     */
    public com.archforce.ath.rds.grpc.proto.CommonParams getCommonParams() {
      if (commonParamsBuilder_ == null) {
        return commonParams_ == null ? com.archforce.ath.rds.grpc.proto.CommonParams.getDefaultInstance() : commonParams_;
      } else {
        return commonParamsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
     */
    public Builder setCommonParams(com.archforce.ath.rds.grpc.proto.CommonParams value) {
      if (commonParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        commonParams_ = value;
        onChanged();
      } else {
        commonParamsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
     */
    public Builder setCommonParams(
        com.archforce.ath.rds.grpc.proto.CommonParams.Builder builderForValue) {
      if (commonParamsBuilder_ == null) {
        commonParams_ = builderForValue.build();
        onChanged();
      } else {
        commonParamsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
     */
    public Builder mergeCommonParams(com.archforce.ath.rds.grpc.proto.CommonParams value) {
      if (commonParamsBuilder_ == null) {
        if (commonParams_ != null) {
          commonParams_ =
            com.archforce.ath.rds.grpc.proto.CommonParams.newBuilder(commonParams_).mergeFrom(value).buildPartial();
        } else {
          commonParams_ = value;
        }
        onChanged();
      } else {
        commonParamsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
     */
    public Builder clearCommonParams() {
      if (commonParamsBuilder_ == null) {
        commonParams_ = null;
        onChanged();
      } else {
        commonParams_ = null;
        commonParamsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
     */
    public com.archforce.ath.rds.grpc.proto.CommonParams.Builder getCommonParamsBuilder() {
      
      onChanged();
      return getCommonParamsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
     */
    public com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder getCommonParamsOrBuilder() {
      if (commonParamsBuilder_ != null) {
        return commonParamsBuilder_.getMessageOrBuilder();
      } else {
        return commonParams_ == null ?
            com.archforce.ath.rds.grpc.proto.CommonParams.getDefaultInstance() : commonParams_;
      }
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.archforce.ath.rds.grpc.proto.CommonParams, com.archforce.ath.rds.grpc.proto.CommonParams.Builder, com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder> 
        getCommonParamsFieldBuilder() {
      if (commonParamsBuilder_ == null) {
        commonParamsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.archforce.ath.rds.grpc.proto.CommonParams, com.archforce.ath.rds.grpc.proto.CommonParams.Builder, com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder>(
                getCommonParams(),
                getParentForChildren(),
                isClean());
        commonParams_ = null;
      }
      return commonParamsBuilder_;
    }

    private int queryResultCode_ ;
    /**
     * <pre>
     * 查询结果代码
     * </pre>
     *
     * <code>int32 queryResultCode = 3;</code>
     */
    public int getQueryResultCode() {
      return queryResultCode_;
    }
    /**
     * <pre>
     * 查询结果代码
     * </pre>
     *
     * <code>int32 queryResultCode = 3;</code>
     */
    public Builder setQueryResultCode(int value) {
      
      queryResultCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 查询结果代码
     * </pre>
     *
     * <code>int32 queryResultCode = 3;</code>
     */
    public Builder clearQueryResultCode() {
      
      queryResultCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object userInfo_ = "";
    /**
     * <pre>
     * 用户私有信息
     * </pre>
     *
     * <code>string userInfo = 4;</code>
     */
    public java.lang.String getUserInfo() {
      java.lang.Object ref = userInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户私有信息
     * </pre>
     *
     * <code>string userInfo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserInfoBytes() {
      java.lang.Object ref = userInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户私有信息
     * </pre>
     *
     * <code>string userInfo = 4;</code>
     */
    public Builder setUserInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户私有信息
     * </pre>
     *
     * <code>string userInfo = 4;</code>
     */
    public Builder clearUserInfo() {
      
      userInfo_ = getDefaultInstance().getUserInfo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户私有信息
     * </pre>
     *
     * <code>string userInfo = 4;</code>
     */
    public Builder setUserInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userInfo_ = value;
      onChanged();
      return this;
    }

    private long lastIndex_ ;
    /**
     * <pre>
     * 条目索引号 最后一笔查询结果的索引号,当"lastIndex+1=totalNum"时表示已经查询到最后的记录;组合个数为0时,该值为-1
     * </pre>
     *
     * <code>int64 lastIndex = 5;</code>
     */
    public long getLastIndex() {
      return lastIndex_;
    }
    /**
     * <pre>
     * 条目索引号 最后一笔查询结果的索引号,当"lastIndex+1=totalNum"时表示已经查询到最后的记录;组合个数为0时,该值为-1
     * </pre>
     *
     * <code>int64 lastIndex = 5;</code>
     */
    public Builder setLastIndex(long value) {
      
      lastIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 条目索引号 最后一笔查询结果的索引号,当"lastIndex+1=totalNum"时表示已经查询到最后的记录;组合个数为0时,该值为-1
     * </pre>
     *
     * <code>int64 lastIndex = 5;</code>
     */
    public Builder clearLastIndex() {
      
      lastIndex_ = 0L;
      onChanged();
      return this;
    }

    private long totalNum_ ;
    /**
     * <pre>
     * 条目总数
     * </pre>
     *
     * <code>int64 totalNum = 6;</code>
     */
    public long getTotalNum() {
      return totalNum_;
    }
    /**
     * <pre>
     * 条目总数
     * </pre>
     *
     * <code>int64 totalNum = 6;</code>
     */
    public Builder setTotalNum(long value) {
      
      totalNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 条目总数
     * </pre>
     *
     * <code>int64 totalNum = 6;</code>
     */
    public Builder clearTotalNum() {
      
      totalNum_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.archforce.ath.rds.grpc.proto.StockInfo> stockInfo_ =
      java.util.Collections.emptyList();
    private void ensureStockInfoIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        stockInfo_ = new java.util.ArrayList<com.archforce.ath.rds.grpc.proto.StockInfo>(stockInfo_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.archforce.ath.rds.grpc.proto.StockInfo, com.archforce.ath.rds.grpc.proto.StockInfo.Builder, com.archforce.ath.rds.grpc.proto.StockInfoOrBuilder> stockInfoBuilder_;

    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public java.util.List<com.archforce.ath.rds.grpc.proto.StockInfo> getStockInfoList() {
      if (stockInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stockInfo_);
      } else {
        return stockInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public int getStockInfoCount() {
      if (stockInfoBuilder_ == null) {
        return stockInfo_.size();
      } else {
        return stockInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public com.archforce.ath.rds.grpc.proto.StockInfo getStockInfo(int index) {
      if (stockInfoBuilder_ == null) {
        return stockInfo_.get(index);
      } else {
        return stockInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public Builder setStockInfo(
        int index, com.archforce.ath.rds.grpc.proto.StockInfo value) {
      if (stockInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStockInfoIsMutable();
        stockInfo_.set(index, value);
        onChanged();
      } else {
        stockInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public Builder setStockInfo(
        int index, com.archforce.ath.rds.grpc.proto.StockInfo.Builder builderForValue) {
      if (stockInfoBuilder_ == null) {
        ensureStockInfoIsMutable();
        stockInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        stockInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public Builder addStockInfo(com.archforce.ath.rds.grpc.proto.StockInfo value) {
      if (stockInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStockInfoIsMutable();
        stockInfo_.add(value);
        onChanged();
      } else {
        stockInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public Builder addStockInfo(
        int index, com.archforce.ath.rds.grpc.proto.StockInfo value) {
      if (stockInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStockInfoIsMutable();
        stockInfo_.add(index, value);
        onChanged();
      } else {
        stockInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public Builder addStockInfo(
        com.archforce.ath.rds.grpc.proto.StockInfo.Builder builderForValue) {
      if (stockInfoBuilder_ == null) {
        ensureStockInfoIsMutable();
        stockInfo_.add(builderForValue.build());
        onChanged();
      } else {
        stockInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public Builder addStockInfo(
        int index, com.archforce.ath.rds.grpc.proto.StockInfo.Builder builderForValue) {
      if (stockInfoBuilder_ == null) {
        ensureStockInfoIsMutable();
        stockInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        stockInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public Builder addAllStockInfo(
        java.lang.Iterable<? extends com.archforce.ath.rds.grpc.proto.StockInfo> values) {
      if (stockInfoBuilder_ == null) {
        ensureStockInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stockInfo_);
        onChanged();
      } else {
        stockInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public Builder clearStockInfo() {
      if (stockInfoBuilder_ == null) {
        stockInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        stockInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public Builder removeStockInfo(int index) {
      if (stockInfoBuilder_ == null) {
        ensureStockInfoIsMutable();
        stockInfo_.remove(index);
        onChanged();
      } else {
        stockInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public com.archforce.ath.rds.grpc.proto.StockInfo.Builder getStockInfoBuilder(
        int index) {
      return getStockInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public com.archforce.ath.rds.grpc.proto.StockInfoOrBuilder getStockInfoOrBuilder(
        int index) {
      if (stockInfoBuilder_ == null) {
        return stockInfo_.get(index);  } else {
        return stockInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public java.util.List<? extends com.archforce.ath.rds.grpc.proto.StockInfoOrBuilder> 
         getStockInfoOrBuilderList() {
      if (stockInfoBuilder_ != null) {
        return stockInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stockInfo_);
      }
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public com.archforce.ath.rds.grpc.proto.StockInfo.Builder addStockInfoBuilder() {
      return getStockInfoFieldBuilder().addBuilder(
          com.archforce.ath.rds.grpc.proto.StockInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public com.archforce.ath.rds.grpc.proto.StockInfo.Builder addStockInfoBuilder(
        int index) {
      return getStockInfoFieldBuilder().addBuilder(
          index, com.archforce.ath.rds.grpc.proto.StockInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
     */
    public java.util.List<com.archforce.ath.rds.grpc.proto.StockInfo.Builder> 
         getStockInfoBuilderList() {
      return getStockInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.archforce.ath.rds.grpc.proto.StockInfo, com.archforce.ath.rds.grpc.proto.StockInfo.Builder, com.archforce.ath.rds.grpc.proto.StockInfoOrBuilder> 
        getStockInfoFieldBuilder() {
      if (stockInfoBuilder_ == null) {
        stockInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.archforce.ath.rds.grpc.proto.StockInfo, com.archforce.ath.rds.grpc.proto.StockInfo.Builder, com.archforce.ath.rds.grpc.proto.StockInfoOrBuilder>(
                stockInfo_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        stockInfo_ = null;
      }
      return stockInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams)
  }

  // @@protoc_insertion_point(class_scope:com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams)
  private static final com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams();
  }

  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryStockInfoResponseParams>
      PARSER = new com.google.protobuf.AbstractParser<QueryStockInfoResponseParams>() {
    public QueryStockInfoResponseParams parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueryStockInfoResponseParams(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryStockInfoResponseParams> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryStockInfoResponseParams> getParserForType() {
    return PARSER;
  }

  public com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

