// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.archforce.ath.rds.grpc.proto;

public interface QueryStockInfoResponseParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.QueryStockInfoResponseParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.MessageType messageType = 1;</code>
   */
  int getMessageTypeValue();
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.MessageType messageType = 1;</code>
   */
  com.archforce.ath.rds.grpc.proto.MessageType getMessageType();

  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
   */
  boolean hasCommonParams();
  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
   */
  com.archforce.ath.rds.grpc.proto.CommonParams getCommonParams();
  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 2;</code>
   */
  com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder getCommonParamsOrBuilder();

  /**
   * <pre>
   * 查询结果代码
   * </pre>
   *
   * <code>int32 queryResultCode = 3;</code>
   */
  int getQueryResultCode();

  /**
   * <pre>
   * 用户私有信息
   * </pre>
   *
   * <code>string userInfo = 4;</code>
   */
  java.lang.String getUserInfo();
  /**
   * <pre>
   * 用户私有信息
   * </pre>
   *
   * <code>string userInfo = 4;</code>
   */
  com.google.protobuf.ByteString
      getUserInfoBytes();

  /**
   * <pre>
   * 条目索引号 最后一笔查询结果的索引号,当"lastIndex+1=totalNum"时表示已经查询到最后的记录;组合个数为0时,该值为-1
   * </pre>
   *
   * <code>int64 lastIndex = 5;</code>
   */
  long getLastIndex();

  /**
   * <pre>
   * 条目总数
   * </pre>
   *
   * <code>int64 totalNum = 6;</code>
   */
  long getTotalNum();

  /**
   * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
   */
  java.util.List<com.archforce.ath.rds.grpc.proto.StockInfo> 
      getStockInfoList();
  /**
   * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
   */
  com.archforce.ath.rds.grpc.proto.StockInfo getStockInfo(int index);
  /**
   * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
   */
  int getStockInfoCount();
  /**
   * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
   */
  java.util.List<? extends com.archforce.ath.rds.grpc.proto.StockInfoOrBuilder> 
      getStockInfoOrBuilderList();
  /**
   * <code>repeated .com.archforce.ath.rds.grpc.proto.StockInfo stockInfo = 7;</code>
   */
  com.archforce.ath.rds.grpc.proto.StockInfoOrBuilder getStockInfoOrBuilder(
      int index);
}
