// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.archforce.ath.rds.grpc.proto;

/**
 * <pre>
 * 股份持仓信息
 * </pre>
 *
 * Protobuf type {@code com.archforce.ath.rds.grpc.proto.StockInfo}
 */
public  final class StockInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.archforce.ath.rds.grpc.proto.StockInfo)
    StockInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StockInfo.newBuilder() to construct.
  private StockInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StockInfo() {
    securityId_ = "";
    securitySymbol_ = "";
    market_ = "";
    accountId_ = "";
    initQty_ = 0L;
    leftQty_ = 0L;
    availableQty_ = 0L;
    profitLoss_ = 0L;
    marketValue_ = 0L;
    costPrice_ = 0L;
    initCrdSellBuyShareQty_ = 0L;
    initCrdSellOccupiedAmt_ = 0L;
    curCrdSellOccupiedQty_ = 0L;
    curCrdSellOccupiedAmt_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StockInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            securityId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            securitySymbol_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            market_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            accountId_ = s;
            break;
          }
          case 40: {

            initQty_ = input.readInt64();
            break;
          }
          case 48: {

            leftQty_ = input.readInt64();
            break;
          }
          case 56: {

            availableQty_ = input.readInt64();
            break;
          }
          case 64: {

            profitLoss_ = input.readInt64();
            break;
          }
          case 72: {

            marketValue_ = input.readInt64();
            break;
          }
          case 80: {

            costPrice_ = input.readInt64();
            break;
          }
          case 88: {

            initCrdSellBuyShareQty_ = input.readInt64();
            break;
          }
          case 96: {

            initCrdSellOccupiedAmt_ = input.readInt64();
            break;
          }
          case 104: {

            curCrdSellOccupiedQty_ = input.readInt64();
            break;
          }
          case 112: {

            curCrdSellOccupiedAmt_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_StockInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_StockInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.archforce.ath.rds.grpc.proto.StockInfo.class, com.archforce.ath.rds.grpc.proto.StockInfo.Builder.class);
  }

  public static final int SECURITYID_FIELD_NUMBER = 1;
  private volatile java.lang.Object securityId_;
  /**
   * <pre>
   * 证券代码
   * </pre>
   *
   * <code>string securityId = 1;</code>
   */
  public java.lang.String getSecurityId() {
    java.lang.Object ref = securityId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      securityId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 证券代码
   * </pre>
   *
   * <code>string securityId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSecurityIdBytes() {
    java.lang.Object ref = securityId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      securityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECURITYSYMBOL_FIELD_NUMBER = 2;
  private volatile java.lang.Object securitySymbol_;
  /**
   * <pre>
   * 证券简称
   * </pre>
   *
   * <code>string securitySymbol = 2;</code>
   */
  public java.lang.String getSecuritySymbol() {
    java.lang.Object ref = securitySymbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      securitySymbol_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 证券简称
   * </pre>
   *
   * <code>string securitySymbol = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSecuritySymbolBytes() {
    java.lang.Object ref = securitySymbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      securitySymbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MARKET_FIELD_NUMBER = 3;
  private volatile java.lang.Object market_;
  /**
   * <pre>
   * 市场
   * </pre>
   *
   * <code>string market = 3;</code>
   */
  public java.lang.String getMarket() {
    java.lang.Object ref = market_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      market_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 市场
   * </pre>
   *
   * <code>string market = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMarketBytes() {
    java.lang.Object ref = market_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      market_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNTID_FIELD_NUMBER = 4;
  private volatile java.lang.Object accountId_;
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>string accountId = 4;</code>
   */
  public java.lang.String getAccountId() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>string accountId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAccountIdBytes() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INITQTY_FIELD_NUMBER = 5;
  private long initQty_;
  /**
   * <pre>
   * 日初持仓量
   * </pre>
   *
   * <code>int64 initQty = 5;</code>
   */
  public long getInitQty() {
    return initQty_;
  }

  public static final int LEFTQTY_FIELD_NUMBER = 6;
  private long leftQty_;
  /**
   * <pre>
   * 剩余股份数量
   * </pre>
   *
   * <code>int64 leftQty = 6;</code>
   */
  public long getLeftQty() {
    return leftQty_;
  }

  public static final int AVAILABLEQTY_FIELD_NUMBER = 7;
  private long availableQty_;
  /**
   * <pre>
   * 可用股份数量
   * </pre>
   *
   * <code>int64 availableQty = 7;</code>
   */
  public long getAvailableQty() {
    return availableQty_;
  }

  public static final int PROFITLOSS_FIELD_NUMBER = 8;
  private long profitLoss_;
  /**
   * <pre>
   * 浮动盈亏
   * </pre>
   *
   * <code>int64 profitLoss = 8;</code>
   */
  public long getProfitLoss() {
    return profitLoss_;
  }

  public static final int MARKETVALUE_FIELD_NUMBER = 9;
  private long marketValue_;
  /**
   * <pre>
   * 市值
   * </pre>
   *
   * <code>int64 marketValue = 9;</code>
   */
  public long getMarketValue() {
    return marketValue_;
  }

  public static final int COSTPRICE_FIELD_NUMBER = 10;
  private long costPrice_;
  /**
   * <pre>
   * 成本价 元/每张
   * </pre>
   *
   * <code>int64 costPrice = 10;</code>
   */
  public long getCostPrice() {
    return costPrice_;
  }

  public static final int INITCRDSELLBUYSHAREQTY_FIELD_NUMBER = 11;
  private long initCrdSellBuyShareQty_;
  /**
   * <pre>
   * 日初融券买入量
   * </pre>
   *
   * <code>int64 initCrdSellBuyShareQty = 11;</code>
   */
  public long getInitCrdSellBuyShareQty() {
    return initCrdSellBuyShareQty_;
  }

  public static final int INITCRDSELLOCCUPIEDAMT_FIELD_NUMBER = 12;
  private long initCrdSellOccupiedAmt_;
  /**
   * <pre>
   * 日初融券占用金额
   * </pre>
   *
   * <code>int64 initCrdSellOccupiedAmt = 12;</code>
   */
  public long getInitCrdSellOccupiedAmt() {
    return initCrdSellOccupiedAmt_;
  }

  public static final int CURCRDSELLOCCUPIEDQTY_FIELD_NUMBER = 13;
  private long curCrdSellOccupiedQty_;
  /**
   * <pre>
   * 当前融券买入量
   * </pre>
   *
   * <code>int64 curCrdSellOccupiedQty = 13;</code>
   */
  public long getCurCrdSellOccupiedQty() {
    return curCrdSellOccupiedQty_;
  }

  public static final int CURCRDSELLOCCUPIEDAMT_FIELD_NUMBER = 14;
  private long curCrdSellOccupiedAmt_;
  /**
   * <pre>
   * 当前融券占用金额
   * </pre>
   *
   * <code>int64 curCrdSellOccupiedAmt = 14;</code>
   */
  public long getCurCrdSellOccupiedAmt() {
    return curCrdSellOccupiedAmt_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSecurityIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, securityId_);
    }
    if (!getSecuritySymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, securitySymbol_);
    }
    if (!getMarketBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, market_);
    }
    if (!getAccountIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accountId_);
    }
    if (initQty_ != 0L) {
      output.writeInt64(5, initQty_);
    }
    if (leftQty_ != 0L) {
      output.writeInt64(6, leftQty_);
    }
    if (availableQty_ != 0L) {
      output.writeInt64(7, availableQty_);
    }
    if (profitLoss_ != 0L) {
      output.writeInt64(8, profitLoss_);
    }
    if (marketValue_ != 0L) {
      output.writeInt64(9, marketValue_);
    }
    if (costPrice_ != 0L) {
      output.writeInt64(10, costPrice_);
    }
    if (initCrdSellBuyShareQty_ != 0L) {
      output.writeInt64(11, initCrdSellBuyShareQty_);
    }
    if (initCrdSellOccupiedAmt_ != 0L) {
      output.writeInt64(12, initCrdSellOccupiedAmt_);
    }
    if (curCrdSellOccupiedQty_ != 0L) {
      output.writeInt64(13, curCrdSellOccupiedQty_);
    }
    if (curCrdSellOccupiedAmt_ != 0L) {
      output.writeInt64(14, curCrdSellOccupiedAmt_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSecurityIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, securityId_);
    }
    if (!getSecuritySymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, securitySymbol_);
    }
    if (!getMarketBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, market_);
    }
    if (!getAccountIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, accountId_);
    }
    if (initQty_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, initQty_);
    }
    if (leftQty_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, leftQty_);
    }
    if (availableQty_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, availableQty_);
    }
    if (profitLoss_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, profitLoss_);
    }
    if (marketValue_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, marketValue_);
    }
    if (costPrice_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, costPrice_);
    }
    if (initCrdSellBuyShareQty_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, initCrdSellBuyShareQty_);
    }
    if (initCrdSellOccupiedAmt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, initCrdSellOccupiedAmt_);
    }
    if (curCrdSellOccupiedQty_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, curCrdSellOccupiedQty_);
    }
    if (curCrdSellOccupiedAmt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(14, curCrdSellOccupiedAmt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.archforce.ath.rds.grpc.proto.StockInfo)) {
      return super.equals(obj);
    }
    com.archforce.ath.rds.grpc.proto.StockInfo other = (com.archforce.ath.rds.grpc.proto.StockInfo) obj;

    boolean result = true;
    result = result && getSecurityId()
        .equals(other.getSecurityId());
    result = result && getSecuritySymbol()
        .equals(other.getSecuritySymbol());
    result = result && getMarket()
        .equals(other.getMarket());
    result = result && getAccountId()
        .equals(other.getAccountId());
    result = result && (getInitQty()
        == other.getInitQty());
    result = result && (getLeftQty()
        == other.getLeftQty());
    result = result && (getAvailableQty()
        == other.getAvailableQty());
    result = result && (getProfitLoss()
        == other.getProfitLoss());
    result = result && (getMarketValue()
        == other.getMarketValue());
    result = result && (getCostPrice()
        == other.getCostPrice());
    result = result && (getInitCrdSellBuyShareQty()
        == other.getInitCrdSellBuyShareQty());
    result = result && (getInitCrdSellOccupiedAmt()
        == other.getInitCrdSellOccupiedAmt());
    result = result && (getCurCrdSellOccupiedQty()
        == other.getCurCrdSellOccupiedQty());
    result = result && (getCurCrdSellOccupiedAmt()
        == other.getCurCrdSellOccupiedAmt());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SECURITYID_FIELD_NUMBER;
    hash = (53 * hash) + getSecurityId().hashCode();
    hash = (37 * hash) + SECURITYSYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSecuritySymbol().hashCode();
    hash = (37 * hash) + MARKET_FIELD_NUMBER;
    hash = (53 * hash) + getMarket().hashCode();
    hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
    hash = (53 * hash) + getAccountId().hashCode();
    hash = (37 * hash) + INITQTY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInitQty());
    hash = (37 * hash) + LEFTQTY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLeftQty());
    hash = (37 * hash) + AVAILABLEQTY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAvailableQty());
    hash = (37 * hash) + PROFITLOSS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProfitLoss());
    hash = (37 * hash) + MARKETVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMarketValue());
    hash = (37 * hash) + COSTPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCostPrice());
    hash = (37 * hash) + INITCRDSELLBUYSHAREQTY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInitCrdSellBuyShareQty());
    hash = (37 * hash) + INITCRDSELLOCCUPIEDAMT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInitCrdSellOccupiedAmt());
    hash = (37 * hash) + CURCRDSELLOCCUPIEDQTY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurCrdSellOccupiedQty());
    hash = (37 * hash) + CURCRDSELLOCCUPIEDAMT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurCrdSellOccupiedAmt());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.archforce.ath.rds.grpc.proto.StockInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.archforce.ath.rds.grpc.proto.StockInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.StockInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.archforce.ath.rds.grpc.proto.StockInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.StockInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.archforce.ath.rds.grpc.proto.StockInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.StockInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.archforce.ath.rds.grpc.proto.StockInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.StockInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.archforce.ath.rds.grpc.proto.StockInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.StockInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.archforce.ath.rds.grpc.proto.StockInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.archforce.ath.rds.grpc.proto.StockInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 股份持仓信息
   * </pre>
   *
   * Protobuf type {@code com.archforce.ath.rds.grpc.proto.StockInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.archforce.ath.rds.grpc.proto.StockInfo)
      com.archforce.ath.rds.grpc.proto.StockInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_StockInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_StockInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.archforce.ath.rds.grpc.proto.StockInfo.class, com.archforce.ath.rds.grpc.proto.StockInfo.Builder.class);
    }

    // Construct using com.archforce.ath.rds.grpc.proto.StockInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      securityId_ = "";

      securitySymbol_ = "";

      market_ = "";

      accountId_ = "";

      initQty_ = 0L;

      leftQty_ = 0L;

      availableQty_ = 0L;

      profitLoss_ = 0L;

      marketValue_ = 0L;

      costPrice_ = 0L;

      initCrdSellBuyShareQty_ = 0L;

      initCrdSellOccupiedAmt_ = 0L;

      curCrdSellOccupiedQty_ = 0L;

      curCrdSellOccupiedAmt_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_StockInfo_descriptor;
    }

    public com.archforce.ath.rds.grpc.proto.StockInfo getDefaultInstanceForType() {
      return com.archforce.ath.rds.grpc.proto.StockInfo.getDefaultInstance();
    }

    public com.archforce.ath.rds.grpc.proto.StockInfo build() {
      com.archforce.ath.rds.grpc.proto.StockInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.archforce.ath.rds.grpc.proto.StockInfo buildPartial() {
      com.archforce.ath.rds.grpc.proto.StockInfo result = new com.archforce.ath.rds.grpc.proto.StockInfo(this);
      result.securityId_ = securityId_;
      result.securitySymbol_ = securitySymbol_;
      result.market_ = market_;
      result.accountId_ = accountId_;
      result.initQty_ = initQty_;
      result.leftQty_ = leftQty_;
      result.availableQty_ = availableQty_;
      result.profitLoss_ = profitLoss_;
      result.marketValue_ = marketValue_;
      result.costPrice_ = costPrice_;
      result.initCrdSellBuyShareQty_ = initCrdSellBuyShareQty_;
      result.initCrdSellOccupiedAmt_ = initCrdSellOccupiedAmt_;
      result.curCrdSellOccupiedQty_ = curCrdSellOccupiedQty_;
      result.curCrdSellOccupiedAmt_ = curCrdSellOccupiedAmt_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.archforce.ath.rds.grpc.proto.StockInfo) {
        return mergeFrom((com.archforce.ath.rds.grpc.proto.StockInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.archforce.ath.rds.grpc.proto.StockInfo other) {
      if (other == com.archforce.ath.rds.grpc.proto.StockInfo.getDefaultInstance()) return this;
      if (!other.getSecurityId().isEmpty()) {
        securityId_ = other.securityId_;
        onChanged();
      }
      if (!other.getSecuritySymbol().isEmpty()) {
        securitySymbol_ = other.securitySymbol_;
        onChanged();
      }
      if (!other.getMarket().isEmpty()) {
        market_ = other.market_;
        onChanged();
      }
      if (!other.getAccountId().isEmpty()) {
        accountId_ = other.accountId_;
        onChanged();
      }
      if (other.getInitQty() != 0L) {
        setInitQty(other.getInitQty());
      }
      if (other.getLeftQty() != 0L) {
        setLeftQty(other.getLeftQty());
      }
      if (other.getAvailableQty() != 0L) {
        setAvailableQty(other.getAvailableQty());
      }
      if (other.getProfitLoss() != 0L) {
        setProfitLoss(other.getProfitLoss());
      }
      if (other.getMarketValue() != 0L) {
        setMarketValue(other.getMarketValue());
      }
      if (other.getCostPrice() != 0L) {
        setCostPrice(other.getCostPrice());
      }
      if (other.getInitCrdSellBuyShareQty() != 0L) {
        setInitCrdSellBuyShareQty(other.getInitCrdSellBuyShareQty());
      }
      if (other.getInitCrdSellOccupiedAmt() != 0L) {
        setInitCrdSellOccupiedAmt(other.getInitCrdSellOccupiedAmt());
      }
      if (other.getCurCrdSellOccupiedQty() != 0L) {
        setCurCrdSellOccupiedQty(other.getCurCrdSellOccupiedQty());
      }
      if (other.getCurCrdSellOccupiedAmt() != 0L) {
        setCurCrdSellOccupiedAmt(other.getCurCrdSellOccupiedAmt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.archforce.ath.rds.grpc.proto.StockInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.archforce.ath.rds.grpc.proto.StockInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object securityId_ = "";
    /**
     * <pre>
     * 证券代码
     * </pre>
     *
     * <code>string securityId = 1;</code>
     */
    public java.lang.String getSecurityId() {
      java.lang.Object ref = securityId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securityId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 证券代码
     * </pre>
     *
     * <code>string securityId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSecurityIdBytes() {
      java.lang.Object ref = securityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 证券代码
     * </pre>
     *
     * <code>string securityId = 1;</code>
     */
    public Builder setSecurityId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      securityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 证券代码
     * </pre>
     *
     * <code>string securityId = 1;</code>
     */
    public Builder clearSecurityId() {
      
      securityId_ = getDefaultInstance().getSecurityId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 证券代码
     * </pre>
     *
     * <code>string securityId = 1;</code>
     */
    public Builder setSecurityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      securityId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object securitySymbol_ = "";
    /**
     * <pre>
     * 证券简称
     * </pre>
     *
     * <code>string securitySymbol = 2;</code>
     */
    public java.lang.String getSecuritySymbol() {
      java.lang.Object ref = securitySymbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securitySymbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 证券简称
     * </pre>
     *
     * <code>string securitySymbol = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSecuritySymbolBytes() {
      java.lang.Object ref = securitySymbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securitySymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 证券简称
     * </pre>
     *
     * <code>string securitySymbol = 2;</code>
     */
    public Builder setSecuritySymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      securitySymbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 证券简称
     * </pre>
     *
     * <code>string securitySymbol = 2;</code>
     */
    public Builder clearSecuritySymbol() {
      
      securitySymbol_ = getDefaultInstance().getSecuritySymbol();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 证券简称
     * </pre>
     *
     * <code>string securitySymbol = 2;</code>
     */
    public Builder setSecuritySymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      securitySymbol_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object market_ = "";
    /**
     * <pre>
     * 市场
     * </pre>
     *
     * <code>string market = 3;</code>
     */
    public java.lang.String getMarket() {
      java.lang.Object ref = market_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        market_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 市场
     * </pre>
     *
     * <code>string market = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMarketBytes() {
      java.lang.Object ref = market_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        market_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 市场
     * </pre>
     *
     * <code>string market = 3;</code>
     */
    public Builder setMarket(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      market_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 市场
     * </pre>
     *
     * <code>string market = 3;</code>
     */
    public Builder clearMarket() {
      
      market_ = getDefaultInstance().getMarket();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 市场
     * </pre>
     *
     * <code>string market = 3;</code>
     */
    public Builder setMarketBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      market_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object accountId_ = "";
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>string accountId = 4;</code>
     */
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>string accountId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>string accountId = 4;</code>
     */
    public Builder setAccountId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>string accountId = 4;</code>
     */
    public Builder clearAccountId() {
      
      accountId_ = getDefaultInstance().getAccountId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>string accountId = 4;</code>
     */
    public Builder setAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountId_ = value;
      onChanged();
      return this;
    }

    private long initQty_ ;
    /**
     * <pre>
     * 日初持仓量
     * </pre>
     *
     * <code>int64 initQty = 5;</code>
     */
    public long getInitQty() {
      return initQty_;
    }
    /**
     * <pre>
     * 日初持仓量
     * </pre>
     *
     * <code>int64 initQty = 5;</code>
     */
    public Builder setInitQty(long value) {
      
      initQty_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 日初持仓量
     * </pre>
     *
     * <code>int64 initQty = 5;</code>
     */
    public Builder clearInitQty() {
      
      initQty_ = 0L;
      onChanged();
      return this;
    }

    private long leftQty_ ;
    /**
     * <pre>
     * 剩余股份数量
     * </pre>
     *
     * <code>int64 leftQty = 6;</code>
     */
    public long getLeftQty() {
      return leftQty_;
    }
    /**
     * <pre>
     * 剩余股份数量
     * </pre>
     *
     * <code>int64 leftQty = 6;</code>
     */
    public Builder setLeftQty(long value) {
      
      leftQty_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 剩余股份数量
     * </pre>
     *
     * <code>int64 leftQty = 6;</code>
     */
    public Builder clearLeftQty() {
      
      leftQty_ = 0L;
      onChanged();
      return this;
    }

    private long availableQty_ ;
    /**
     * <pre>
     * 可用股份数量
     * </pre>
     *
     * <code>int64 availableQty = 7;</code>
     */
    public long getAvailableQty() {
      return availableQty_;
    }
    /**
     * <pre>
     * 可用股份数量
     * </pre>
     *
     * <code>int64 availableQty = 7;</code>
     */
    public Builder setAvailableQty(long value) {
      
      availableQty_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 可用股份数量
     * </pre>
     *
     * <code>int64 availableQty = 7;</code>
     */
    public Builder clearAvailableQty() {
      
      availableQty_ = 0L;
      onChanged();
      return this;
    }

    private long profitLoss_ ;
    /**
     * <pre>
     * 浮动盈亏
     * </pre>
     *
     * <code>int64 profitLoss = 8;</code>
     */
    public long getProfitLoss() {
      return profitLoss_;
    }
    /**
     * <pre>
     * 浮动盈亏
     * </pre>
     *
     * <code>int64 profitLoss = 8;</code>
     */
    public Builder setProfitLoss(long value) {
      
      profitLoss_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 浮动盈亏
     * </pre>
     *
     * <code>int64 profitLoss = 8;</code>
     */
    public Builder clearProfitLoss() {
      
      profitLoss_ = 0L;
      onChanged();
      return this;
    }

    private long marketValue_ ;
    /**
     * <pre>
     * 市值
     * </pre>
     *
     * <code>int64 marketValue = 9;</code>
     */
    public long getMarketValue() {
      return marketValue_;
    }
    /**
     * <pre>
     * 市值
     * </pre>
     *
     * <code>int64 marketValue = 9;</code>
     */
    public Builder setMarketValue(long value) {
      
      marketValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 市值
     * </pre>
     *
     * <code>int64 marketValue = 9;</code>
     */
    public Builder clearMarketValue() {
      
      marketValue_ = 0L;
      onChanged();
      return this;
    }

    private long costPrice_ ;
    /**
     * <pre>
     * 成本价 元/每张
     * </pre>
     *
     * <code>int64 costPrice = 10;</code>
     */
    public long getCostPrice() {
      return costPrice_;
    }
    /**
     * <pre>
     * 成本价 元/每张
     * </pre>
     *
     * <code>int64 costPrice = 10;</code>
     */
    public Builder setCostPrice(long value) {
      
      costPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 成本价 元/每张
     * </pre>
     *
     * <code>int64 costPrice = 10;</code>
     */
    public Builder clearCostPrice() {
      
      costPrice_ = 0L;
      onChanged();
      return this;
    }

    private long initCrdSellBuyShareQty_ ;
    /**
     * <pre>
     * 日初融券买入量
     * </pre>
     *
     * <code>int64 initCrdSellBuyShareQty = 11;</code>
     */
    public long getInitCrdSellBuyShareQty() {
      return initCrdSellBuyShareQty_;
    }
    /**
     * <pre>
     * 日初融券买入量
     * </pre>
     *
     * <code>int64 initCrdSellBuyShareQty = 11;</code>
     */
    public Builder setInitCrdSellBuyShareQty(long value) {
      
      initCrdSellBuyShareQty_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 日初融券买入量
     * </pre>
     *
     * <code>int64 initCrdSellBuyShareQty = 11;</code>
     */
    public Builder clearInitCrdSellBuyShareQty() {
      
      initCrdSellBuyShareQty_ = 0L;
      onChanged();
      return this;
    }

    private long initCrdSellOccupiedAmt_ ;
    /**
     * <pre>
     * 日初融券占用金额
     * </pre>
     *
     * <code>int64 initCrdSellOccupiedAmt = 12;</code>
     */
    public long getInitCrdSellOccupiedAmt() {
      return initCrdSellOccupiedAmt_;
    }
    /**
     * <pre>
     * 日初融券占用金额
     * </pre>
     *
     * <code>int64 initCrdSellOccupiedAmt = 12;</code>
     */
    public Builder setInitCrdSellOccupiedAmt(long value) {
      
      initCrdSellOccupiedAmt_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 日初融券占用金额
     * </pre>
     *
     * <code>int64 initCrdSellOccupiedAmt = 12;</code>
     */
    public Builder clearInitCrdSellOccupiedAmt() {
      
      initCrdSellOccupiedAmt_ = 0L;
      onChanged();
      return this;
    }

    private long curCrdSellOccupiedQty_ ;
    /**
     * <pre>
     * 当前融券买入量
     * </pre>
     *
     * <code>int64 curCrdSellOccupiedQty = 13;</code>
     */
    public long getCurCrdSellOccupiedQty() {
      return curCrdSellOccupiedQty_;
    }
    /**
     * <pre>
     * 当前融券买入量
     * </pre>
     *
     * <code>int64 curCrdSellOccupiedQty = 13;</code>
     */
    public Builder setCurCrdSellOccupiedQty(long value) {
      
      curCrdSellOccupiedQty_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前融券买入量
     * </pre>
     *
     * <code>int64 curCrdSellOccupiedQty = 13;</code>
     */
    public Builder clearCurCrdSellOccupiedQty() {
      
      curCrdSellOccupiedQty_ = 0L;
      onChanged();
      return this;
    }

    private long curCrdSellOccupiedAmt_ ;
    /**
     * <pre>
     * 当前融券占用金额
     * </pre>
     *
     * <code>int64 curCrdSellOccupiedAmt = 14;</code>
     */
    public long getCurCrdSellOccupiedAmt() {
      return curCrdSellOccupiedAmt_;
    }
    /**
     * <pre>
     * 当前融券占用金额
     * </pre>
     *
     * <code>int64 curCrdSellOccupiedAmt = 14;</code>
     */
    public Builder setCurCrdSellOccupiedAmt(long value) {
      
      curCrdSellOccupiedAmt_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前融券占用金额
     * </pre>
     *
     * <code>int64 curCrdSellOccupiedAmt = 14;</code>
     */
    public Builder clearCurCrdSellOccupiedAmt() {
      
      curCrdSellOccupiedAmt_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.archforce.ath.rds.grpc.proto.StockInfo)
  }

  // @@protoc_insertion_point(class_scope:com.archforce.ath.rds.grpc.proto.StockInfo)
  private static final com.archforce.ath.rds.grpc.proto.StockInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.archforce.ath.rds.grpc.proto.StockInfo();
  }

  public static com.archforce.ath.rds.grpc.proto.StockInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StockInfo>
      PARSER = new com.google.protobuf.AbstractParser<StockInfo>() {
    public StockInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StockInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StockInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StockInfo> getParserForType() {
    return PARSER;
  }

  public com.archforce.ath.rds.grpc.proto.StockInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

