// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.archforce.ath.rds.grpc.proto;

public interface UserIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.UserId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   */
  long getUserId();
}
