// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.archforce.ath.rds.grpc.proto;

public final class UserServiceOuterClass {
  private UserServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_archforce_ath_rds_grpc_proto_AddUserInfoParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_archforce_ath_rds_grpc_proto_AddUserInfoParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_archforce_ath_rds_grpc_proto_UserId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_archforce_ath_rds_grpc_proto_UserId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserService.proto\022 com.archforce.ath.r" +
      "ds.grpc.proto\"%\n\021AddUserInfoParams\022\020\n\010us" +
      "ername\030\001 \001(\t\"\030\n\006UserId\022\016\n\006userId\030\001 \001(\0032{" +
      "\n\013UserService\022l\n\013addUserInfo\0223.com.archf" +
      "orce.ath.rds.grpc.proto.AddUserInfoParam" +
      "s\032(.com.archforce.ath.rds.grpc.proto.Use" +
      "rIdB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_archforce_ath_rds_grpc_proto_AddUserInfoParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_archforce_ath_rds_grpc_proto_AddUserInfoParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_archforce_ath_rds_grpc_proto_AddUserInfoParams_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_archforce_ath_rds_grpc_proto_UserId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_archforce_ath_rds_grpc_proto_UserId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_archforce_ath_rds_grpc_proto_UserId_descriptor,
        new java.lang.String[] { "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
