// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package com.archforce.ath.rds.grpc.proto;

public interface A1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.A1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 1;</code>
   */
  int getA();

  /**
   * <code>int32 b = 2;</code>
   */
  int getB();
}
