// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package com.archforce.ath.rds.grpc.proto;

public interface A2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.A2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 message = 1;</code>
   */
  int getMessage();
}
