// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package com.archforce.ath.rds.grpc.proto;

public interface A3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.A3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 i = 1;</code>
   */
  java.util.List<java.lang.Integer> getIList();
  /**
   * <code>repeated int32 i = 1;</code>
   */
  int getICount();
  /**
   * <code>repeated int32 i = 1;</code>
   */
  int getI(int index);
}
