// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.archforce.ath.rds.grpc.proto;

/**
 * <pre>
 * 业务类型
 * </pre>
 *
 * Protobuf enum {@code com.archforce.ath.rds.grpc.proto.BusinessType}
 */
public enum BusinessType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 现金拍卖
   * </pre>
   *
   * <code>CASH_AUCTION = 0;</code>
   */
  CASH_AUCTION(0),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 现金拍卖
   * </pre>
   *
   * <code>CASH_AUCTION = 0;</code>
   */
  public static final int CASH_AUCTION_VALUE = 0;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static BusinessType valueOf(int value) {
    return forNumber(value);
  }

  public static BusinessType forNumber(int value) {
    switch (value) {
      case 0: return CASH_AUCTION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<BusinessType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      BusinessType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<BusinessType>() {
          public BusinessType findValueByNumber(int number) {
            return BusinessType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final BusinessType[] VALUES = values();

  public static BusinessType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private BusinessType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.archforce.ath.rds.grpc.proto.BusinessType)
}

