// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientManage.proto

package com.archforce.ath.rds.grpc.proto;

public final class ClientManageOuterClass {
  private ClientManageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_archforce_ath_rds_grpc_proto_ClientInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_archforce_ath_rds_grpc_proto_ClientInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_archforce_ath_rds_grpc_proto_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_archforce_ath_rds_grpc_proto_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ClientManage.proto\022 com.archforce.ath." +
      "rds.grpc.proto\"B\n\nClientInfo\022\020\n\010clientId" +
      "\030\001 \001(\t\022\020\n\010username\030\002 \001(\t\022\020\n\010password\030\003 \001" +
      "(\t\")\n\007Message\022\r\n\005msgId\030\001 \001(\003\022\017\n\007message\030" +
      "\002 \001(\t2\313\002\n\014ClientManage\022h\n\rloginToServer\022" +
      ",.com.archforce.ath.rds.grpc.proto.Clien" +
      "tInfo\032).com.archforce.ath.rds.grpc.proto" +
      ".Message\022k\n\020logoutFromServer\022,.com.archf" +
      "orce.ath.rds.grpc.proto.ClientInfo\032).com" +
      ".archforce.ath.rds.grpc.proto.Message\022d\n" +
      "\007sendMsg\022,.com.archforce.ath.rds.grpc.pr" +
      "oto.ClientInfo\032).com.archforce.ath.rds.g" +
      "rpc.proto.Message0\001B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_archforce_ath_rds_grpc_proto_ClientInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_archforce_ath_rds_grpc_proto_ClientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_archforce_ath_rds_grpc_proto_ClientInfo_descriptor,
        new java.lang.String[] { "ClientId", "Username", "Password", });
    internal_static_com_archforce_ath_rds_grpc_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_archforce_ath_rds_grpc_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_archforce_ath_rds_grpc_proto_Message_descriptor,
        new java.lang.String[] { "MsgId", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
