// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientManage.proto

package com.archforce.ath.rds.grpc.proto;

public interface ClientInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.ClientInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientId = 1;</code>
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
