// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.archforce.ath.rds.grpc.proto;

/**
 * <pre>
 * 公共参数
 * </pre>
 *
 * Protobuf type {@code com.archforce.ath.rds.grpc.proto.CommonParams}
 */
public  final class CommonParams extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.archforce.ath.rds.grpc.proto.CommonParams)
    CommonParamsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommonParams.newBuilder() to construct.
  private CommonParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommonParams() {
    custId_ = "";
    fundAccountId_ = "";
    accountId_ = "";
    clientSeqId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CommonParams(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            custId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            fundAccountId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            accountId_ = s;
            break;
          }
          case 40: {

            clientSeqId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_CommonParams_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_CommonParams_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.archforce.ath.rds.grpc.proto.CommonParams.class, com.archforce.ath.rds.grpc.proto.CommonParams.Builder.class);
  }

  public static final int CUSTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object custId_;
  /**
   * <pre>
   * 客户号
   * </pre>
   *
   * <code>string custId = 2;</code>
   */
  public java.lang.String getCustId() {
    java.lang.Object ref = custId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      custId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 客户号
   * </pre>
   *
   * <code>string custId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCustIdBytes() {
    java.lang.Object ref = custId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      custId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FUNDACCOUNTID_FIELD_NUMBER = 3;
  private volatile java.lang.Object fundAccountId_;
  /**
   * <pre>
   * 资金账号
   * </pre>
   *
   * <code>string fundAccountId = 3;</code>
   */
  public java.lang.String getFundAccountId() {
    java.lang.Object ref = fundAccountId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fundAccountId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 资金账号
   * </pre>
   *
   * <code>string fundAccountId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getFundAccountIdBytes() {
    java.lang.Object ref = fundAccountId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fundAccountId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNTID_FIELD_NUMBER = 4;
  private volatile java.lang.Object accountId_;
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>string accountId = 4;</code>
   */
  public java.lang.String getAccountId() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>string accountId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAccountIdBytes() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTSEQID_FIELD_NUMBER = 5;
  private long clientSeqId_;
  /**
   * <pre>
   * 用户系统消息序号
   * </pre>
   *
   * <code>int64 clientSeqId = 5;</code>
   */
  public long getClientSeqId() {
    return clientSeqId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCustIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, custId_);
    }
    if (!getFundAccountIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fundAccountId_);
    }
    if (!getAccountIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accountId_);
    }
    if (clientSeqId_ != 0L) {
      output.writeInt64(5, clientSeqId_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCustIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, custId_);
    }
    if (!getFundAccountIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fundAccountId_);
    }
    if (!getAccountIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, accountId_);
    }
    if (clientSeqId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, clientSeqId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.archforce.ath.rds.grpc.proto.CommonParams)) {
      return super.equals(obj);
    }
    com.archforce.ath.rds.grpc.proto.CommonParams other = (com.archforce.ath.rds.grpc.proto.CommonParams) obj;

    boolean result = true;
    result = result && getCustId()
        .equals(other.getCustId());
    result = result && getFundAccountId()
        .equals(other.getFundAccountId());
    result = result && getAccountId()
        .equals(other.getAccountId());
    result = result && (getClientSeqId()
        == other.getClientSeqId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CUSTID_FIELD_NUMBER;
    hash = (53 * hash) + getCustId().hashCode();
    hash = (37 * hash) + FUNDACCOUNTID_FIELD_NUMBER;
    hash = (53 * hash) + getFundAccountId().hashCode();
    hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
    hash = (53 * hash) + getAccountId().hashCode();
    hash = (37 * hash) + CLIENTSEQID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getClientSeqId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.archforce.ath.rds.grpc.proto.CommonParams parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.archforce.ath.rds.grpc.proto.CommonParams parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.CommonParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.archforce.ath.rds.grpc.proto.CommonParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.CommonParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.archforce.ath.rds.grpc.proto.CommonParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.CommonParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.archforce.ath.rds.grpc.proto.CommonParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.CommonParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.archforce.ath.rds.grpc.proto.CommonParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.CommonParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.archforce.ath.rds.grpc.proto.CommonParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.archforce.ath.rds.grpc.proto.CommonParams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * Protobuf type {@code com.archforce.ath.rds.grpc.proto.CommonParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.archforce.ath.rds.grpc.proto.CommonParams)
      com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_CommonParams_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_CommonParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.archforce.ath.rds.grpc.proto.CommonParams.class, com.archforce.ath.rds.grpc.proto.CommonParams.Builder.class);
    }

    // Construct using com.archforce.ath.rds.grpc.proto.CommonParams.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      custId_ = "";

      fundAccountId_ = "";

      accountId_ = "";

      clientSeqId_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_CommonParams_descriptor;
    }

    public com.archforce.ath.rds.grpc.proto.CommonParams getDefaultInstanceForType() {
      return com.archforce.ath.rds.grpc.proto.CommonParams.getDefaultInstance();
    }

    public com.archforce.ath.rds.grpc.proto.CommonParams build() {
      com.archforce.ath.rds.grpc.proto.CommonParams result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.archforce.ath.rds.grpc.proto.CommonParams buildPartial() {
      com.archforce.ath.rds.grpc.proto.CommonParams result = new com.archforce.ath.rds.grpc.proto.CommonParams(this);
      result.custId_ = custId_;
      result.fundAccountId_ = fundAccountId_;
      result.accountId_ = accountId_;
      result.clientSeqId_ = clientSeqId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.archforce.ath.rds.grpc.proto.CommonParams) {
        return mergeFrom((com.archforce.ath.rds.grpc.proto.CommonParams)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.archforce.ath.rds.grpc.proto.CommonParams other) {
      if (other == com.archforce.ath.rds.grpc.proto.CommonParams.getDefaultInstance()) return this;
      if (!other.getCustId().isEmpty()) {
        custId_ = other.custId_;
        onChanged();
      }
      if (!other.getFundAccountId().isEmpty()) {
        fundAccountId_ = other.fundAccountId_;
        onChanged();
      }
      if (!other.getAccountId().isEmpty()) {
        accountId_ = other.accountId_;
        onChanged();
      }
      if (other.getClientSeqId() != 0L) {
        setClientSeqId(other.getClientSeqId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.archforce.ath.rds.grpc.proto.CommonParams parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.archforce.ath.rds.grpc.proto.CommonParams) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object custId_ = "";
    /**
     * <pre>
     * 客户号
     * </pre>
     *
     * <code>string custId = 2;</code>
     */
    public java.lang.String getCustId() {
      java.lang.Object ref = custId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        custId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 客户号
     * </pre>
     *
     * <code>string custId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCustIdBytes() {
      java.lang.Object ref = custId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        custId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 客户号
     * </pre>
     *
     * <code>string custId = 2;</code>
     */
    public Builder setCustId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      custId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户号
     * </pre>
     *
     * <code>string custId = 2;</code>
     */
    public Builder clearCustId() {
      
      custId_ = getDefaultInstance().getCustId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户号
     * </pre>
     *
     * <code>string custId = 2;</code>
     */
    public Builder setCustIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      custId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fundAccountId_ = "";
    /**
     * <pre>
     * 资金账号
     * </pre>
     *
     * <code>string fundAccountId = 3;</code>
     */
    public java.lang.String getFundAccountId() {
      java.lang.Object ref = fundAccountId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fundAccountId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 资金账号
     * </pre>
     *
     * <code>string fundAccountId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFundAccountIdBytes() {
      java.lang.Object ref = fundAccountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fundAccountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 资金账号
     * </pre>
     *
     * <code>string fundAccountId = 3;</code>
     */
    public Builder setFundAccountId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fundAccountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资金账号
     * </pre>
     *
     * <code>string fundAccountId = 3;</code>
     */
    public Builder clearFundAccountId() {
      
      fundAccountId_ = getDefaultInstance().getFundAccountId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 资金账号
     * </pre>
     *
     * <code>string fundAccountId = 3;</code>
     */
    public Builder setFundAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fundAccountId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object accountId_ = "";
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>string accountId = 4;</code>
     */
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>string accountId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>string accountId = 4;</code>
     */
    public Builder setAccountId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>string accountId = 4;</code>
     */
    public Builder clearAccountId() {
      
      accountId_ = getDefaultInstance().getAccountId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>string accountId = 4;</code>
     */
    public Builder setAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountId_ = value;
      onChanged();
      return this;
    }

    private long clientSeqId_ ;
    /**
     * <pre>
     * 用户系统消息序号
     * </pre>
     *
     * <code>int64 clientSeqId = 5;</code>
     */
    public long getClientSeqId() {
      return clientSeqId_;
    }
    /**
     * <pre>
     * 用户系统消息序号
     * </pre>
     *
     * <code>int64 clientSeqId = 5;</code>
     */
    public Builder setClientSeqId(long value) {
      
      clientSeqId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户系统消息序号
     * </pre>
     *
     * <code>int64 clientSeqId = 5;</code>
     */
    public Builder clearClientSeqId() {
      
      clientSeqId_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.archforce.ath.rds.grpc.proto.CommonParams)
  }

  // @@protoc_insertion_point(class_scope:com.archforce.ath.rds.grpc.proto.CommonParams)
  private static final com.archforce.ath.rds.grpc.proto.CommonParams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.archforce.ath.rds.grpc.proto.CommonParams();
  }

  public static com.archforce.ath.rds.grpc.proto.CommonParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommonParams>
      PARSER = new com.google.protobuf.AbstractParser<CommonParams>() {
    public CommonParams parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CommonParams(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommonParams> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommonParams> getParserForType() {
    return PARSER;
  }

  public com.archforce.ath.rds.grpc.proto.CommonParams getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

