// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.archforce.ath.rds.grpc.proto;

public interface CommonParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.CommonParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 客户号
   * </pre>
   *
   * <code>string custId = 2;</code>
   */
  java.lang.String getCustId();
  /**
   * <pre>
   * 客户号
   * </pre>
   *
   * <code>string custId = 2;</code>
   */
  com.google.protobuf.ByteString
      getCustIdBytes();

  /**
   * <pre>
   * 资金账号
   * </pre>
   *
   * <code>string fundAccountId = 3;</code>
   */
  java.lang.String getFundAccountId();
  /**
   * <pre>
   * 资金账号
   * </pre>
   *
   * <code>string fundAccountId = 3;</code>
   */
  com.google.protobuf.ByteString
      getFundAccountIdBytes();

  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>string accountId = 4;</code>
   */
  java.lang.String getAccountId();
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>string accountId = 4;</code>
   */
  com.google.protobuf.ByteString
      getAccountIdBytes();

  /**
   * <pre>
   * 用户系统消息序号
   * </pre>
   *
   * <code>int64 clientSeqId = 5;</code>
   */
  long getClientSeqId();
}
