// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientManage.proto

package com.archforce.ath.rds.grpc.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 msgId = 1;</code>
   */
  long getMsgId();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
