// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.archforce.ath.rds.grpc.proto;

/**
 * <pre>
 * 消息类型
 * </pre>
 *
 * Protobuf enum {@code com.archforce.ath.rds.grpc.proto.MessageType}
 */
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 原消息兼容格式
   * </pre>
   *
   * <code>ORIGINAL_MESSAGE = 0;</code>
   */
  ORIGINAL_MESSAGE(0),
  /**
   * <pre>
   * 订单消息
   * </pre>
   *
   * <code>ORDER_MESSAGE = 1;</code>
   */
  ORDER_MESSAGE(1),
  /**
   * <pre>
   * 回报消息
   * </pre>
   *
   * <code>REPORT_MESSAGE = 2;</code>
   */
  REPORT_MESSAGE(2),
  /**
   * <pre>
   * 外部查询消息
   * </pre>
   *
   * <code>OUT_QUERY_MESSAGE = 3;</code>
   */
  OUT_QUERY_MESSAGE(3),
  /**
   * <pre>
   * 行情消息
   * </pre>
   *
   * <code>MARKET_MESSAGE = 4;</code>
   */
  MARKET_MESSAGE(4),
  /**
   * <pre>
   * 时间片、探测、登出登出等功能消息
   * </pre>
   *
   * <code>FUNCTION_MESSAGE = 5;</code>
   */
  FUNCTION_MESSAGE(5),
  /**
   * <pre>
   * 实时指令消息
   * </pre>
   *
   * <code>REAL_TIME_COMMAND_MESSAGE = 6;</code>
   */
  REAL_TIME_COMMAND_MESSAGE(6),
  /**
   * <pre>
   * 撤单消息
   * </pre>
   *
   * <code>REPEAL_ORDER_MESSAGE = 7;</code>
   */
  REPEAL_ORDER_MESSAGE(7),
  /**
   * <pre>
   * 定制化消息
   * </pre>
   *
   * <code>CUSTOMIZE_MESSAGE = 8;</code>
   */
  CUSTOMIZE_MESSAGE(8),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 原消息兼容格式
   * </pre>
   *
   * <code>ORIGINAL_MESSAGE = 0;</code>
   */
  public static final int ORIGINAL_MESSAGE_VALUE = 0;
  /**
   * <pre>
   * 订单消息
   * </pre>
   *
   * <code>ORDER_MESSAGE = 1;</code>
   */
  public static final int ORDER_MESSAGE_VALUE = 1;
  /**
   * <pre>
   * 回报消息
   * </pre>
   *
   * <code>REPORT_MESSAGE = 2;</code>
   */
  public static final int REPORT_MESSAGE_VALUE = 2;
  /**
   * <pre>
   * 外部查询消息
   * </pre>
   *
   * <code>OUT_QUERY_MESSAGE = 3;</code>
   */
  public static final int OUT_QUERY_MESSAGE_VALUE = 3;
  /**
   * <pre>
   * 行情消息
   * </pre>
   *
   * <code>MARKET_MESSAGE = 4;</code>
   */
  public static final int MARKET_MESSAGE_VALUE = 4;
  /**
   * <pre>
   * 时间片、探测、登出登出等功能消息
   * </pre>
   *
   * <code>FUNCTION_MESSAGE = 5;</code>
   */
  public static final int FUNCTION_MESSAGE_VALUE = 5;
  /**
   * <pre>
   * 实时指令消息
   * </pre>
   *
   * <code>REAL_TIME_COMMAND_MESSAGE = 6;</code>
   */
  public static final int REAL_TIME_COMMAND_MESSAGE_VALUE = 6;
  /**
   * <pre>
   * 撤单消息
   * </pre>
   *
   * <code>REPEAL_ORDER_MESSAGE = 7;</code>
   */
  public static final int REPEAL_ORDER_MESSAGE_VALUE = 7;
  /**
   * <pre>
   * 定制化消息
   * </pre>
   *
   * <code>CUSTOMIZE_MESSAGE = 8;</code>
   */
  public static final int CUSTOMIZE_MESSAGE_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return ORIGINAL_MESSAGE;
      case 1: return ORDER_MESSAGE;
      case 2: return REPORT_MESSAGE;
      case 3: return OUT_QUERY_MESSAGE;
      case 4: return MARKET_MESSAGE;
      case 5: return FUNCTION_MESSAGE;
      case 6: return REAL_TIME_COMMAND_MESSAGE;
      case 7: return REPEAL_ORDER_MESSAGE;
      case 8: return CUSTOMIZE_MESSAGE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.archforce.ath.rds.grpc.proto.MessageType)
}

