// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.archforce.ath.rds.grpc.proto;

public interface QueryStockInfoRequestParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
   */
  boolean hasCommonParams();
  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
   */
  com.archforce.ath.rds.grpc.proto.CommonParams getCommonParams();
  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
   */
  com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder getCommonParamsOrBuilder();

  /**
   * <pre>
   * 终端识别码
   * </pre>
   *
   * <code>string clientFeatureCode = 2;</code>
   */
  java.lang.String getClientFeatureCode();
  /**
   * <pre>
   * 终端识别码
   * </pre>
   *
   * <code>string clientFeatureCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientFeatureCodeBytes();

  /**
   * <pre>
   * 用户私有信息
   * </pre>
   *
   * <code>string userInfo = 3;</code>
   */
  java.lang.String getUserInfo();
  /**
   * <pre>
   * 用户私有信息
   * </pre>
   *
   * <code>string userInfo = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserInfoBytes();

  /**
   * <pre>
   * 密码
   * </pre>
   *
   * <code>string password = 4;</code>
   */
  java.lang.String getPassword();
  /**
   * <pre>
   * 密码
   * </pre>
   *
   * <code>string password = 4;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>repeated string accountIds = 5;</code>
   */
  java.util.List<java.lang.String>
      getAccountIdsList();
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>repeated string accountIds = 5;</code>
   */
  int getAccountIdsCount();
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>repeated string accountIds = 5;</code>
   */
  java.lang.String getAccountIds(int index);
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>repeated string accountIds = 5;</code>
   */
  com.google.protobuf.ByteString
      getAccountIdsBytes(int index);

  /**
   * <pre>
   * 业务类型
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.BusinessType businessType = 6;</code>
   */
  int getBusinessTypeValue();
  /**
   * <pre>
   * 业务类型
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.BusinessType businessType = 6;</code>
   */
  com.archforce.ath.rds.grpc.proto.BusinessType getBusinessType();

  /**
   * <pre>
   * 市场
   * </pre>
   *
   * <code>string market = 7;</code>
   */
  java.lang.String getMarket();
  /**
   * <pre>
   * 市场
   * </pre>
   *
   * <code>string market = 7;</code>
   */
  com.google.protobuf.ByteString
      getMarketBytes();

  /**
   * <pre>
   * 证券代码
   * </pre>
   *
   * <code>string securityId = 8;</code>
   */
  java.lang.String getSecurityId();
  /**
   * <pre>
   * 证券代码
   * </pre>
   *
   * <code>string securityId = 8;</code>
   */
  com.google.protobuf.ByteString
      getSecurityIdBytes();

  /**
   * <pre>
   * 分页记录号 指定起始查询索引号,将返回索引号以后的明细,默认0表示从头开始查
   * </pre>
   *
   * <code>int64 queryIndex = 9;</code>
   */
  long getQueryIndex();

  /**
   * <pre>
   * 返回数量 默认0表示不指定
   * </pre>
   *
   * <code>int64 returnNum = 10;</code>
   */
  long getReturnNum();
}
