// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.archforce.ath.rds.grpc.proto;

public interface QueryStockInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.QueryStockInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 返回json字符串
   * </pre>
   *
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <pre>
   * 返回json字符串
   * </pre>
   *
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
