// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.archforce.ath.rds.grpc.proto;

/**
 * <pre>
 * 查询股份持仓信息请求参数
 * </pre>
 *
 * Protobuf type {@code com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams}
 */
public  final class QueryStockInfoRequestParams extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams)
    QueryStockInfoRequestParamsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryStockInfoRequestParams.newBuilder() to construct.
  private QueryStockInfoRequestParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryStockInfoRequestParams() {
    clientFeatureCode_ = "";
    userInfo_ = "";
    password_ = "";
    accountIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    businessType_ = 0;
    market_ = "";
    securityId_ = "";
    queryIndex_ = 0L;
    returnNum_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryStockInfoRequestParams(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.archforce.ath.rds.grpc.proto.CommonParams.Builder subBuilder = null;
            if (commonParams_ != null) {
              subBuilder = commonParams_.toBuilder();
            }
            commonParams_ = input.readMessage(com.archforce.ath.rds.grpc.proto.CommonParams.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(commonParams_);
              commonParams_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            clientFeatureCode_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            userInfo_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              accountIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            accountIds_.add(s);
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            businessType_ = rawValue;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            market_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            securityId_ = s;
            break;
          }
          case 72: {

            queryIndex_ = input.readInt64();
            break;
          }
          case 80: {

            returnNum_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        accountIds_ = accountIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoRequestParams_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoRequestParams_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams.class, com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams.Builder.class);
  }

  private int bitField0_;
  public static final int COMMONPARAMS_FIELD_NUMBER = 1;
  private com.archforce.ath.rds.grpc.proto.CommonParams commonParams_;
  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
   */
  public boolean hasCommonParams() {
    return commonParams_ != null;
  }
  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
   */
  public com.archforce.ath.rds.grpc.proto.CommonParams getCommonParams() {
    return commonParams_ == null ? com.archforce.ath.rds.grpc.proto.CommonParams.getDefaultInstance() : commonParams_;
  }
  /**
   * <pre>
   * 公共参数
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
   */
  public com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder getCommonParamsOrBuilder() {
    return getCommonParams();
  }

  public static final int CLIENTFEATURECODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object clientFeatureCode_;
  /**
   * <pre>
   * 终端识别码
   * </pre>
   *
   * <code>string clientFeatureCode = 2;</code>
   */
  public java.lang.String getClientFeatureCode() {
    java.lang.Object ref = clientFeatureCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientFeatureCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 终端识别码
   * </pre>
   *
   * <code>string clientFeatureCode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getClientFeatureCodeBytes() {
    java.lang.Object ref = clientFeatureCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientFeatureCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERINFO_FIELD_NUMBER = 3;
  private volatile java.lang.Object userInfo_;
  /**
   * <pre>
   * 用户私有信息
   * </pre>
   *
   * <code>string userInfo = 3;</code>
   */
  public java.lang.String getUserInfo() {
    java.lang.Object ref = userInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userInfo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户私有信息
   * </pre>
   *
   * <code>string userInfo = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUserInfoBytes() {
    java.lang.Object ref = userInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 4;
  private volatile java.lang.Object password_;
  /**
   * <pre>
   * 密码
   * </pre>
   *
   * <code>string password = 4;</code>
   */
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 密码
   * </pre>
   *
   * <code>string password = 4;</code>
   */
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNTIDS_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList accountIds_;
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>repeated string accountIds = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getAccountIdsList() {
    return accountIds_;
  }
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>repeated string accountIds = 5;</code>
   */
  public int getAccountIdsCount() {
    return accountIds_.size();
  }
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>repeated string accountIds = 5;</code>
   */
  public java.lang.String getAccountIds(int index) {
    return accountIds_.get(index);
  }
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>repeated string accountIds = 5;</code>
   */
  public com.google.protobuf.ByteString
      getAccountIdsBytes(int index) {
    return accountIds_.getByteString(index);
  }

  public static final int BUSINESSTYPE_FIELD_NUMBER = 6;
  private int businessType_;
  /**
   * <pre>
   * 业务类型
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.BusinessType businessType = 6;</code>
   */
  public int getBusinessTypeValue() {
    return businessType_;
  }
  /**
   * <pre>
   * 业务类型
   * </pre>
   *
   * <code>.com.archforce.ath.rds.grpc.proto.BusinessType businessType = 6;</code>
   */
  public com.archforce.ath.rds.grpc.proto.BusinessType getBusinessType() {
    com.archforce.ath.rds.grpc.proto.BusinessType result = com.archforce.ath.rds.grpc.proto.BusinessType.valueOf(businessType_);
    return result == null ? com.archforce.ath.rds.grpc.proto.BusinessType.UNRECOGNIZED : result;
  }

  public static final int MARKET_FIELD_NUMBER = 7;
  private volatile java.lang.Object market_;
  /**
   * <pre>
   * 市场
   * </pre>
   *
   * <code>string market = 7;</code>
   */
  public java.lang.String getMarket() {
    java.lang.Object ref = market_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      market_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 市场
   * </pre>
   *
   * <code>string market = 7;</code>
   */
  public com.google.protobuf.ByteString
      getMarketBytes() {
    java.lang.Object ref = market_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      market_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECURITYID_FIELD_NUMBER = 8;
  private volatile java.lang.Object securityId_;
  /**
   * <pre>
   * 证券代码
   * </pre>
   *
   * <code>string securityId = 8;</code>
   */
  public java.lang.String getSecurityId() {
    java.lang.Object ref = securityId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      securityId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 证券代码
   * </pre>
   *
   * <code>string securityId = 8;</code>
   */
  public com.google.protobuf.ByteString
      getSecurityIdBytes() {
    java.lang.Object ref = securityId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      securityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUERYINDEX_FIELD_NUMBER = 9;
  private long queryIndex_;
  /**
   * <pre>
   * 分页记录号 指定起始查询索引号,将返回索引号以后的明细,默认0表示从头开始查
   * </pre>
   *
   * <code>int64 queryIndex = 9;</code>
   */
  public long getQueryIndex() {
    return queryIndex_;
  }

  public static final int RETURNNUM_FIELD_NUMBER = 10;
  private long returnNum_;
  /**
   * <pre>
   * 返回数量 默认0表示不指定
   * </pre>
   *
   * <code>int64 returnNum = 10;</code>
   */
  public long getReturnNum() {
    return returnNum_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (commonParams_ != null) {
      output.writeMessage(1, getCommonParams());
    }
    if (!getClientFeatureCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientFeatureCode_);
    }
    if (!getUserInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userInfo_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, password_);
    }
    for (int i = 0; i < accountIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, accountIds_.getRaw(i));
    }
    if (businessType_ != com.archforce.ath.rds.grpc.proto.BusinessType.CASH_AUCTION.getNumber()) {
      output.writeEnum(6, businessType_);
    }
    if (!getMarketBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, market_);
    }
    if (!getSecurityIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, securityId_);
    }
    if (queryIndex_ != 0L) {
      output.writeInt64(9, queryIndex_);
    }
    if (returnNum_ != 0L) {
      output.writeInt64(10, returnNum_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (commonParams_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCommonParams());
    }
    if (!getClientFeatureCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientFeatureCode_);
    }
    if (!getUserInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userInfo_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, password_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < accountIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(accountIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAccountIdsList().size();
    }
    if (businessType_ != com.archforce.ath.rds.grpc.proto.BusinessType.CASH_AUCTION.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, businessType_);
    }
    if (!getMarketBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, market_);
    }
    if (!getSecurityIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, securityId_);
    }
    if (queryIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, queryIndex_);
    }
    if (returnNum_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, returnNum_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams)) {
      return super.equals(obj);
    }
    com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams other = (com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams) obj;

    boolean result = true;
    result = result && (hasCommonParams() == other.hasCommonParams());
    if (hasCommonParams()) {
      result = result && getCommonParams()
          .equals(other.getCommonParams());
    }
    result = result && getClientFeatureCode()
        .equals(other.getClientFeatureCode());
    result = result && getUserInfo()
        .equals(other.getUserInfo());
    result = result && getPassword()
        .equals(other.getPassword());
    result = result && getAccountIdsList()
        .equals(other.getAccountIdsList());
    result = result && businessType_ == other.businessType_;
    result = result && getMarket()
        .equals(other.getMarket());
    result = result && getSecurityId()
        .equals(other.getSecurityId());
    result = result && (getQueryIndex()
        == other.getQueryIndex());
    result = result && (getReturnNum()
        == other.getReturnNum());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCommonParams()) {
      hash = (37 * hash) + COMMONPARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getCommonParams().hashCode();
    }
    hash = (37 * hash) + CLIENTFEATURECODE_FIELD_NUMBER;
    hash = (53 * hash) + getClientFeatureCode().hashCode();
    hash = (37 * hash) + USERINFO_FIELD_NUMBER;
    hash = (53 * hash) + getUserInfo().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    if (getAccountIdsCount() > 0) {
      hash = (37 * hash) + ACCOUNTIDS_FIELD_NUMBER;
      hash = (53 * hash) + getAccountIdsList().hashCode();
    }
    hash = (37 * hash) + BUSINESSTYPE_FIELD_NUMBER;
    hash = (53 * hash) + businessType_;
    hash = (37 * hash) + MARKET_FIELD_NUMBER;
    hash = (53 * hash) + getMarket().hashCode();
    hash = (37 * hash) + SECURITYID_FIELD_NUMBER;
    hash = (53 * hash) + getSecurityId().hashCode();
    hash = (37 * hash) + QUERYINDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getQueryIndex());
    hash = (37 * hash) + RETURNNUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReturnNum());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 查询股份持仓信息请求参数
   * </pre>
   *
   * Protobuf type {@code com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams)
      com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParamsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoRequestParams_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoRequestParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams.class, com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams.Builder.class);
    }

    // Construct using com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (commonParamsBuilder_ == null) {
        commonParams_ = null;
      } else {
        commonParams_ = null;
        commonParamsBuilder_ = null;
      }
      clientFeatureCode_ = "";

      userInfo_ = "";

      password_ = "";

      accountIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      businessType_ = 0;

      market_ = "";

      securityId_ = "";

      queryIndex_ = 0L;

      returnNum_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.archforce.ath.rds.grpc.proto.StockServiceOuterClass.internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoRequestParams_descriptor;
    }

    public com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams getDefaultInstanceForType() {
      return com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams.getDefaultInstance();
    }

    public com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams build() {
      com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams buildPartial() {
      com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams result = new com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (commonParamsBuilder_ == null) {
        result.commonParams_ = commonParams_;
      } else {
        result.commonParams_ = commonParamsBuilder_.build();
      }
      result.clientFeatureCode_ = clientFeatureCode_;
      result.userInfo_ = userInfo_;
      result.password_ = password_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        accountIds_ = accountIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.accountIds_ = accountIds_;
      result.businessType_ = businessType_;
      result.market_ = market_;
      result.securityId_ = securityId_;
      result.queryIndex_ = queryIndex_;
      result.returnNum_ = returnNum_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams) {
        return mergeFrom((com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams other) {
      if (other == com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams.getDefaultInstance()) return this;
      if (other.hasCommonParams()) {
        mergeCommonParams(other.getCommonParams());
      }
      if (!other.getClientFeatureCode().isEmpty()) {
        clientFeatureCode_ = other.clientFeatureCode_;
        onChanged();
      }
      if (!other.getUserInfo().isEmpty()) {
        userInfo_ = other.userInfo_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.accountIds_.isEmpty()) {
        if (accountIds_.isEmpty()) {
          accountIds_ = other.accountIds_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureAccountIdsIsMutable();
          accountIds_.addAll(other.accountIds_);
        }
        onChanged();
      }
      if (other.businessType_ != 0) {
        setBusinessTypeValue(other.getBusinessTypeValue());
      }
      if (!other.getMarket().isEmpty()) {
        market_ = other.market_;
        onChanged();
      }
      if (!other.getSecurityId().isEmpty()) {
        securityId_ = other.securityId_;
        onChanged();
      }
      if (other.getQueryIndex() != 0L) {
        setQueryIndex(other.getQueryIndex());
      }
      if (other.getReturnNum() != 0L) {
        setReturnNum(other.getReturnNum());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.archforce.ath.rds.grpc.proto.CommonParams commonParams_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.archforce.ath.rds.grpc.proto.CommonParams, com.archforce.ath.rds.grpc.proto.CommonParams.Builder, com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder> commonParamsBuilder_;
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
     */
    public boolean hasCommonParams() {
      return commonParamsBuilder_ != null || commonParams_ != null;
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
     */
    public com.archforce.ath.rds.grpc.proto.CommonParams getCommonParams() {
      if (commonParamsBuilder_ == null) {
        return commonParams_ == null ? com.archforce.ath.rds.grpc.proto.CommonParams.getDefaultInstance() : commonParams_;
      } else {
        return commonParamsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
     */
    public Builder setCommonParams(com.archforce.ath.rds.grpc.proto.CommonParams value) {
      if (commonParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        commonParams_ = value;
        onChanged();
      } else {
        commonParamsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
     */
    public Builder setCommonParams(
        com.archforce.ath.rds.grpc.proto.CommonParams.Builder builderForValue) {
      if (commonParamsBuilder_ == null) {
        commonParams_ = builderForValue.build();
        onChanged();
      } else {
        commonParamsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
     */
    public Builder mergeCommonParams(com.archforce.ath.rds.grpc.proto.CommonParams value) {
      if (commonParamsBuilder_ == null) {
        if (commonParams_ != null) {
          commonParams_ =
            com.archforce.ath.rds.grpc.proto.CommonParams.newBuilder(commonParams_).mergeFrom(value).buildPartial();
        } else {
          commonParams_ = value;
        }
        onChanged();
      } else {
        commonParamsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
     */
    public Builder clearCommonParams() {
      if (commonParamsBuilder_ == null) {
        commonParams_ = null;
        onChanged();
      } else {
        commonParams_ = null;
        commonParamsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
     */
    public com.archforce.ath.rds.grpc.proto.CommonParams.Builder getCommonParamsBuilder() {
      
      onChanged();
      return getCommonParamsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
     */
    public com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder getCommonParamsOrBuilder() {
      if (commonParamsBuilder_ != null) {
        return commonParamsBuilder_.getMessageOrBuilder();
      } else {
        return commonParams_ == null ?
            com.archforce.ath.rds.grpc.proto.CommonParams.getDefaultInstance() : commonParams_;
      }
    }
    /**
     * <pre>
     * 公共参数
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.CommonParams commonParams = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.archforce.ath.rds.grpc.proto.CommonParams, com.archforce.ath.rds.grpc.proto.CommonParams.Builder, com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder> 
        getCommonParamsFieldBuilder() {
      if (commonParamsBuilder_ == null) {
        commonParamsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.archforce.ath.rds.grpc.proto.CommonParams, com.archforce.ath.rds.grpc.proto.CommonParams.Builder, com.archforce.ath.rds.grpc.proto.CommonParamsOrBuilder>(
                getCommonParams(),
                getParentForChildren(),
                isClean());
        commonParams_ = null;
      }
      return commonParamsBuilder_;
    }

    private java.lang.Object clientFeatureCode_ = "";
    /**
     * <pre>
     * 终端识别码
     * </pre>
     *
     * <code>string clientFeatureCode = 2;</code>
     */
    public java.lang.String getClientFeatureCode() {
      java.lang.Object ref = clientFeatureCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientFeatureCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 终端识别码
     * </pre>
     *
     * <code>string clientFeatureCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientFeatureCodeBytes() {
      java.lang.Object ref = clientFeatureCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientFeatureCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 终端识别码
     * </pre>
     *
     * <code>string clientFeatureCode = 2;</code>
     */
    public Builder setClientFeatureCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientFeatureCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 终端识别码
     * </pre>
     *
     * <code>string clientFeatureCode = 2;</code>
     */
    public Builder clearClientFeatureCode() {
      
      clientFeatureCode_ = getDefaultInstance().getClientFeatureCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 终端识别码
     * </pre>
     *
     * <code>string clientFeatureCode = 2;</code>
     */
    public Builder setClientFeatureCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientFeatureCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userInfo_ = "";
    /**
     * <pre>
     * 用户私有信息
     * </pre>
     *
     * <code>string userInfo = 3;</code>
     */
    public java.lang.String getUserInfo() {
      java.lang.Object ref = userInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户私有信息
     * </pre>
     *
     * <code>string userInfo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserInfoBytes() {
      java.lang.Object ref = userInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户私有信息
     * </pre>
     *
     * <code>string userInfo = 3;</code>
     */
    public Builder setUserInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户私有信息
     * </pre>
     *
     * <code>string userInfo = 3;</code>
     */
    public Builder clearUserInfo() {
      
      userInfo_ = getDefaultInstance().getUserInfo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户私有信息
     * </pre>
     *
     * <code>string userInfo = 3;</code>
     */
    public Builder setUserInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userInfo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>string password = 4;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>string password = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>string password = 4;</code>
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>string password = 4;</code>
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>string password = 4;</code>
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList accountIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAccountIdsIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        accountIds_ = new com.google.protobuf.LazyStringArrayList(accountIds_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>repeated string accountIds = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAccountIdsList() {
      return accountIds_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>repeated string accountIds = 5;</code>
     */
    public int getAccountIdsCount() {
      return accountIds_.size();
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>repeated string accountIds = 5;</code>
     */
    public java.lang.String getAccountIds(int index) {
      return accountIds_.get(index);
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>repeated string accountIds = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAccountIdsBytes(int index) {
      return accountIds_.getByteString(index);
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>repeated string accountIds = 5;</code>
     */
    public Builder setAccountIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAccountIdsIsMutable();
      accountIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>repeated string accountIds = 5;</code>
     */
    public Builder addAccountIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAccountIdsIsMutable();
      accountIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>repeated string accountIds = 5;</code>
     */
    public Builder addAllAccountIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureAccountIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, accountIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>repeated string accountIds = 5;</code>
     */
    public Builder clearAccountIds() {
      accountIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 股东代码
     * </pre>
     *
     * <code>repeated string accountIds = 5;</code>
     */
    public Builder addAccountIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAccountIdsIsMutable();
      accountIds_.add(value);
      onChanged();
      return this;
    }

    private int businessType_ = 0;
    /**
     * <pre>
     * 业务类型
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.BusinessType businessType = 6;</code>
     */
    public int getBusinessTypeValue() {
      return businessType_;
    }
    /**
     * <pre>
     * 业务类型
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.BusinessType businessType = 6;</code>
     */
    public Builder setBusinessTypeValue(int value) {
      businessType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 业务类型
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.BusinessType businessType = 6;</code>
     */
    public com.archforce.ath.rds.grpc.proto.BusinessType getBusinessType() {
      com.archforce.ath.rds.grpc.proto.BusinessType result = com.archforce.ath.rds.grpc.proto.BusinessType.valueOf(businessType_);
      return result == null ? com.archforce.ath.rds.grpc.proto.BusinessType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 业务类型
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.BusinessType businessType = 6;</code>
     */
    public Builder setBusinessType(com.archforce.ath.rds.grpc.proto.BusinessType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      businessType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 业务类型
     * </pre>
     *
     * <code>.com.archforce.ath.rds.grpc.proto.BusinessType businessType = 6;</code>
     */
    public Builder clearBusinessType() {
      
      businessType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object market_ = "";
    /**
     * <pre>
     * 市场
     * </pre>
     *
     * <code>string market = 7;</code>
     */
    public java.lang.String getMarket() {
      java.lang.Object ref = market_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        market_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 市场
     * </pre>
     *
     * <code>string market = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMarketBytes() {
      java.lang.Object ref = market_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        market_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 市场
     * </pre>
     *
     * <code>string market = 7;</code>
     */
    public Builder setMarket(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      market_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 市场
     * </pre>
     *
     * <code>string market = 7;</code>
     */
    public Builder clearMarket() {
      
      market_ = getDefaultInstance().getMarket();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 市场
     * </pre>
     *
     * <code>string market = 7;</code>
     */
    public Builder setMarketBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      market_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object securityId_ = "";
    /**
     * <pre>
     * 证券代码
     * </pre>
     *
     * <code>string securityId = 8;</code>
     */
    public java.lang.String getSecurityId() {
      java.lang.Object ref = securityId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securityId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 证券代码
     * </pre>
     *
     * <code>string securityId = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSecurityIdBytes() {
      java.lang.Object ref = securityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 证券代码
     * </pre>
     *
     * <code>string securityId = 8;</code>
     */
    public Builder setSecurityId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      securityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 证券代码
     * </pre>
     *
     * <code>string securityId = 8;</code>
     */
    public Builder clearSecurityId() {
      
      securityId_ = getDefaultInstance().getSecurityId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 证券代码
     * </pre>
     *
     * <code>string securityId = 8;</code>
     */
    public Builder setSecurityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      securityId_ = value;
      onChanged();
      return this;
    }

    private long queryIndex_ ;
    /**
     * <pre>
     * 分页记录号 指定起始查询索引号,将返回索引号以后的明细,默认0表示从头开始查
     * </pre>
     *
     * <code>int64 queryIndex = 9;</code>
     */
    public long getQueryIndex() {
      return queryIndex_;
    }
    /**
     * <pre>
     * 分页记录号 指定起始查询索引号,将返回索引号以后的明细,默认0表示从头开始查
     * </pre>
     *
     * <code>int64 queryIndex = 9;</code>
     */
    public Builder setQueryIndex(long value) {
      
      queryIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 分页记录号 指定起始查询索引号,将返回索引号以后的明细,默认0表示从头开始查
     * </pre>
     *
     * <code>int64 queryIndex = 9;</code>
     */
    public Builder clearQueryIndex() {
      
      queryIndex_ = 0L;
      onChanged();
      return this;
    }

    private long returnNum_ ;
    /**
     * <pre>
     * 返回数量 默认0表示不指定
     * </pre>
     *
     * <code>int64 returnNum = 10;</code>
     */
    public long getReturnNum() {
      return returnNum_;
    }
    /**
     * <pre>
     * 返回数量 默认0表示不指定
     * </pre>
     *
     * <code>int64 returnNum = 10;</code>
     */
    public Builder setReturnNum(long value) {
      
      returnNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 返回数量 默认0表示不指定
     * </pre>
     *
     * <code>int64 returnNum = 10;</code>
     */
    public Builder clearReturnNum() {
      
      returnNum_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams)
  }

  // @@protoc_insertion_point(class_scope:com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams)
  private static final com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams();
  }

  public static com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryStockInfoRequestParams>
      PARSER = new com.google.protobuf.AbstractParser<QueryStockInfoRequestParams>() {
    public QueryStockInfoRequestParams parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueryStockInfoRequestParams(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryStockInfoRequestParams> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryStockInfoRequestParams> getParserForType() {
    return PARSER;
  }

  public com.archforce.ath.rds.grpc.proto.QueryStockInfoRequestParams getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

