// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package com.archforce.ath.rds.grpc.proto;

public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
