// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.archforce.ath.rds.grpc.proto;

public interface StockInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.archforce.ath.rds.grpc.proto.StockInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 证券代码
   * </pre>
   *
   * <code>string securityId = 1;</code>
   */
  java.lang.String getSecurityId();
  /**
   * <pre>
   * 证券代码
   * </pre>
   *
   * <code>string securityId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSecurityIdBytes();

  /**
   * <pre>
   * 证券简称
   * </pre>
   *
   * <code>string securitySymbol = 2;</code>
   */
  java.lang.String getSecuritySymbol();
  /**
   * <pre>
   * 证券简称
   * </pre>
   *
   * <code>string securitySymbol = 2;</code>
   */
  com.google.protobuf.ByteString
      getSecuritySymbolBytes();

  /**
   * <pre>
   * 市场
   * </pre>
   *
   * <code>string market = 3;</code>
   */
  java.lang.String getMarket();
  /**
   * <pre>
   * 市场
   * </pre>
   *
   * <code>string market = 3;</code>
   */
  com.google.protobuf.ByteString
      getMarketBytes();

  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>string accountId = 4;</code>
   */
  java.lang.String getAccountId();
  /**
   * <pre>
   * 股东代码
   * </pre>
   *
   * <code>string accountId = 4;</code>
   */
  com.google.protobuf.ByteString
      getAccountIdBytes();

  /**
   * <pre>
   * 日初持仓量
   * </pre>
   *
   * <code>int64 initQty = 5;</code>
   */
  long getInitQty();

  /**
   * <pre>
   * 剩余股份数量
   * </pre>
   *
   * <code>int64 leftQty = 6;</code>
   */
  long getLeftQty();

  /**
   * <pre>
   * 可用股份数量
   * </pre>
   *
   * <code>int64 availableQty = 7;</code>
   */
  long getAvailableQty();

  /**
   * <pre>
   * 浮动盈亏
   * </pre>
   *
   * <code>int64 profitLoss = 8;</code>
   */
  long getProfitLoss();

  /**
   * <pre>
   * 市值
   * </pre>
   *
   * <code>int64 marketValue = 9;</code>
   */
  long getMarketValue();

  /**
   * <pre>
   * 成本价 元/每张
   * </pre>
   *
   * <code>int64 costPrice = 10;</code>
   */
  long getCostPrice();

  /**
   * <pre>
   * 日初融券买入量
   * </pre>
   *
   * <code>int64 initCrdSellBuyShareQty = 11;</code>
   */
  long getInitCrdSellBuyShareQty();

  /**
   * <pre>
   * 日初融券占用金额
   * </pre>
   *
   * <code>int64 initCrdSellOccupiedAmt = 12;</code>
   */
  long getInitCrdSellOccupiedAmt();

  /**
   * <pre>
   * 当前融券买入量
   * </pre>
   *
   * <code>int64 curCrdSellOccupiedQty = 13;</code>
   */
  long getCurCrdSellOccupiedQty();

  /**
   * <pre>
   * 当前融券占用金额
   * </pre>
   *
   * <code>int64 curCrdSellOccupiedAmt = 14;</code>
   */
  long getCurCrdSellOccupiedAmt();
}
