// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.archforce.ath.rds.grpc.proto;

public final class StockServiceOuterClass {
  private StockServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_archforce_ath_rds_grpc_proto_CommonParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_archforce_ath_rds_grpc_proto_CommonParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_archforce_ath_rds_grpc_proto_StockInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_archforce_ath_rds_grpc_proto_StockInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoRequestParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoRequestParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponseParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponseParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022StockService.proto\022 com.archforce.ath." +
      "rds.grpc.proto\"]\n\014CommonParams\022\016\n\006custId" +
      "\030\002 \001(\t\022\025\n\rfundAccountId\030\003 \001(\t\022\021\n\taccount" +
      "Id\030\004 \001(\t\022\023\n\013clientSeqId\030\005 \001(\003\"\314\002\n\tStockI" +
      "nfo\022\022\n\nsecurityId\030\001 \001(\t\022\026\n\016securitySymbo" +
      "l\030\002 \001(\t\022\016\n\006market\030\003 \001(\t\022\021\n\taccountId\030\004 \001" +
      "(\t\022\017\n\007initQty\030\005 \001(\003\022\017\n\007leftQty\030\006 \001(\003\022\024\n\014" +
      "availableQty\030\007 \001(\003\022\022\n\nprofitLoss\030\010 \001(\003\022\023" +
      "\n\013marketValue\030\t \001(\003\022\021\n\tcostPrice\030\n \001(\003\022\036" +
      "\n\026initCrdSellBuyShareQty\030\013 \001(\003\022\036\n\026initCr" +
      "dSellOccupiedAmt\030\014 \001(\003\022\035\n\025curCrdSellOccu" +
      "piedQty\030\r \001(\003\022\035\n\025curCrdSellOccupiedAmt\030\016" +
      " \001(\003\"\307\002\n\033QueryStockInfoRequestParams\022D\n\014" +
      "commonParams\030\001 \001(\0132..com.archforce.ath.r" +
      "ds.grpc.proto.CommonParams\022\031\n\021clientFeat" +
      "ureCode\030\002 \001(\t\022\020\n\010userInfo\030\003 \001(\t\022\020\n\010passw" +
      "ord\030\004 \001(\t\022\022\n\naccountIds\030\005 \003(\t\022D\n\014busines" +
      "sType\030\006 \001(\0162..com.archforce.ath.rds.grpc" +
      ".proto.BusinessType\022\016\n\006market\030\007 \001(\t\022\022\n\ns" +
      "ecurityId\030\010 \001(\t\022\022\n\nqueryIndex\030\t \001(\003\022\021\n\tr" +
      "eturnNum\030\n \001(\003\"\270\002\n\034QueryStockInfoRespons" +
      "eParams\022B\n\013messageType\030\001 \001(\0162-.com.archf" +
      "orce.ath.rds.grpc.proto.MessageType\022D\n\014c" +
      "ommonParams\030\002 \001(\0132..com.archforce.ath.rd" +
      "s.grpc.proto.CommonParams\022\027\n\017queryResult" +
      "Code\030\003 \001(\005\022\020\n\010userInfo\030\004 \001(\t\022\021\n\tlastInde" +
      "x\030\005 \001(\003\022\020\n\010totalNum\030\006 \001(\003\022>\n\tstockInfo\030\007" +
      " \003(\0132+.com.archforce.ath.rds.grpc.proto." +
      "StockInfo\"(\n\026QueryStockInfoResponse\022\016\n\006r" +
      "esult\030\001 \001(\t*\333\001\n\013MessageType\022\024\n\020ORIGINAL_" +
      "MESSAGE\020\000\022\021\n\rORDER_MESSAGE\020\001\022\022\n\016REPORT_M" +
      "ESSAGE\020\002\022\025\n\021OUT_QUERY_MESSAGE\020\003\022\022\n\016MARKE" +
      "T_MESSAGE\020\004\022\024\n\020FUNCTION_MESSAGE\020\005\022\035\n\031REA" +
      "L_TIME_COMMAND_MESSAGE\020\006\022\030\n\024REPEAL_ORDER" +
      "_MESSAGE\020\007\022\025\n\021CUSTOMIZE_MESSAGE\020\010* \n\014Bus" +
      "inessType\022\020\n\014CASH_AUCTION\020\0002\232\001\n\014StockSer" +
      "vice\022\211\001\n\016queryStockInfo\022=.com.archforce." +
      "ath.rds.grpc.proto.QueryStockInfoRequest" +
      "Params\0328.com.archforce.ath.rds.grpc.prot" +
      "o.QueryStockInfoResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_archforce_ath_rds_grpc_proto_CommonParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_archforce_ath_rds_grpc_proto_CommonParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_archforce_ath_rds_grpc_proto_CommonParams_descriptor,
        new java.lang.String[] { "CustId", "FundAccountId", "AccountId", "ClientSeqId", });
    internal_static_com_archforce_ath_rds_grpc_proto_StockInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_archforce_ath_rds_grpc_proto_StockInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_archforce_ath_rds_grpc_proto_StockInfo_descriptor,
        new java.lang.String[] { "SecurityId", "SecuritySymbol", "Market", "AccountId", "InitQty", "LeftQty", "AvailableQty", "ProfitLoss", "MarketValue", "CostPrice", "InitCrdSellBuyShareQty", "InitCrdSellOccupiedAmt", "CurCrdSellOccupiedQty", "CurCrdSellOccupiedAmt", });
    internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoRequestParams_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoRequestParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoRequestParams_descriptor,
        new java.lang.String[] { "CommonParams", "ClientFeatureCode", "UserInfo", "Password", "AccountIds", "BusinessType", "Market", "SecurityId", "QueryIndex", "ReturnNum", });
    internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponseParams_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponseParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponseParams_descriptor,
        new java.lang.String[] { "MessageType", "CommonParams", "QueryResultCode", "UserInfo", "LastIndex", "TotalNum", "StockInfo", });
    internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_archforce_ath_rds_grpc_proto_QueryStockInfoResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
